// Incodex translations for the Codex locale catalog; not vendor CUA translations.
// English and Chinese source copy remains in incognito-copy.ts.
export const ACCESSIBILITY_REGIONAL_COPY = {
  "am": {
    "title": "የChatGPT ስክሪፕት ቁጥጥርን አንቃ",
    "installedTitle": "የChatGPT ስክሪፕት ቁጥጥርን እንደገና አንቃ",
    "body": "Incodexን መጫን ChatGPTን ይለውጠዋል፣ ስለዚህ የተደራሽነት ፈቃዱ እንደገና መሰጠት አለበት።",
    "permissionTitle": "ተደራሽነት",
    "permissionDescription": "የመተግበሪያ በይነገጾችን ማንበብ እና መጠቀም",
    "repair": "ፍቀድ",
    "later": "ዝለል",
    "back": "ተመለስ",
    "addedTitle": "በስርዓት ቅንብሮች ውስጥ ChatGPTን ፍቀድ",
    "addedBody": "ከላይ ያለውን የChatGPT አዶ ወደ የተደራሽነት ዝርዝር ይጎትቱ እና ያንቁት። ማንኛውንም የmacOS ማረጋገጫ ያጠናቁ። መዳረሻው በራስ-ሰር ይመረመራል፤ መዳረሻ ሲዘጋጅ ይህ መስኮት ይዘጋል።",
    "dragInstruction": "የተደራሽነት መዳረሻ ለመፍቀድ ChatGPTን ወደ ከላይ ያለው ዝርዝር ይጎትቱ",
    "completeInSettings": "በስርዓት ቅንብሮች ውስጥ ያጠናቁ",
    "checking": "መዳረሻን በመጠበቅ ላይ · በራስ-ሰር በመመርመር ላይ",
    "repairing": "የስርዓት ቅንብሮችን በማዘጋጀት ላይ…",
    "openSettings": "ቅንብሮችን ክፈት",
    "errorTitle": "የChatGPT ፈቃድ ማዋቀር አልተጠናቀቀም",
    "errorBody": "የፈቃድ ማዋቀሩን ማጠናቀቅ አልተቻለም። /Applications/ChatGPT.appን በስርዓት ቅንብሮች → ግላዊነት እና ደህንነት → ተደራሽነት ውስጥ ያክሉ፣ ከዚያ ለመመርመር incodex installን ያስኪዱ።"
  },
  "ar": {
    "title": "تمكين التحكم في البرامج النصية لـ ChatGPT",
    "installedTitle": "إعادة تمكين التحكم في البرامج النصية لـ ChatGPT",
    "body": "يُعدّل تثبيت Incodex تطبيق ChatGPT، لذا يجب منح إذن إمكانية الوصول له مرة أخرى.",
    "permissionTitle": "تسهيلات الاستخدام",
    "permissionDescription": "قراءة واجهات التطبيقات والتفاعل معها",
    "repair": "السماح",
    "later": "تخطي",
    "back": "رجوع",
    "addedTitle": "السماح لـ ChatGPT في إعدادات النظام",
    "addedBody": "اسحب أيقونة ChatGPT أعلاه إلى قائمة تسهيلات الاستخدام وفعّلها. أكمل أي مصادقة يطلبها macOS. يتم التحقق من الوصول تلقائيًا؛ وستُغلق هذه النافذة عند جاهزية الوصول.",
    "dragInstruction": "اسحب ChatGPT إلى القائمة أعلاه لمنحه إذن تسهيلات الاستخدام",
    "completeInSettings": "إكمال العملية في إعدادات النظام",
    "checking": "في انتظار الوصول · جارٍ التحقق تلقائيًا",
    "repairing": "جارٍ إعداد إعدادات النظام…",
    "openSettings": "فتح الإعدادات",
    "errorTitle": "إعداد أذونات ChatGPT غير مكتمل",
    "errorBody": "تعذّر إكمال إعداد الأذونات. أضف /Applications/ChatGPT.app في إعدادات النظام → الخصوصية والأمان → تسهيلات الاستخدام، ثم شغّل incodex install للتحقق مرة أخرى."
  },
  "bg-BG": {
    "title": "Разрешете управлението на скриптове за ChatGPT",
    "installedTitle": "Разрешете отново управлението на скриптове за ChatGPT",
    "body": "Инсталирането на Incodex променя ChatGPT, затова разрешението за улеснен достъп трябва да бъде дадено отново.",
    "permissionTitle": "Улеснен достъп",
    "permissionDescription": "Четене и взаимодействие с интерфейсите на приложенията",
    "repair": "Разреши",
    "later": "Пропусни",
    "back": "Назад",
    "addedTitle": "Разрешете ChatGPT в Системни настройки",
    "addedBody": "Плъзнете иконата на ChatGPT по-горе в списъка за улеснен достъп и я разрешете. Завършете всяко удостоверяване на macOS. Достъпът се проверява автоматично; този прозорец се затваря, когато достъпът е готов.",
    "dragInstruction": "Плъзнете ChatGPT в списъка по-горе, за да разрешите Улеснен достъп",
    "completeInSettings": "Завършете в Системни настройки",
    "checking": "Изчакване на достъпа · автоматична проверка",
    "repairing": "Подготовка на Системни настройки…",
    "openSettings": "Отвори настройките",
    "errorTitle": "Настройването на разрешенията за ChatGPT не е завършено",
    "errorBody": "Настройването на разрешенията не можа да бъде завършено. Добавете /Applications/ChatGPT.app в Системни настройки → Поверителност и сигурност → Улеснен достъп, след което изпълнете incodex install, за да проверите отново."
  },
  "bn-BD": {
    "title": "ChatGPT স্ক্রিপ্ট নিয়ন্ত্রণ চালু করুন",
    "installedTitle": "ChatGPT স্ক্রিপ্ট নিয়ন্ত্রণ আবার চালু করুন",
    "body": "Incodex ইনস্টল করলে ChatGPT পরিবর্তিত হয়, তাই এর অ্যাক্সেসিবিলিটি অনুমতি আবার দিতে হবে।",
    "permissionTitle": "অ্যাক্সেসিবিলিটি",
    "permissionDescription": "অ্যাপের ইন্টারফেস পড়ুন ও তার সঙ্গে কাজ করুন",
    "repair": "অনুমতি দিন",
    "later": "এড়িয়ে যান",
    "back": "পিছনে",
    "addedTitle": "সিস্টেম সেটিংসে ChatGPT-কে অনুমতি দিন",
    "addedBody": "উপরের ChatGPT আইকনটি অ্যাক্সেসিবিলিটি তালিকায় টেনে এনে চালু করুন। macOS-এর প্রয়োজনীয় যেকোনো প্রমাণীকরণ সম্পূর্ণ করুন। অ্যাক্সেস স্বয়ংক্রিয়ভাবে পরীক্ষা করা হবে; অ্যাক্সেস প্রস্তুত হলে এই উইন্ডোটি বন্ধ হবে।",
    "dragInstruction": "অ্যাক্সেসিবিলিটি অনুমতি দিতে ChatGPT-কে উপরের তালিকায় টেনে আনুন",
    "completeInSettings": "সিস্টেম সেটিংসে সম্পূর্ণ করুন",
    "checking": "অ্যাক্সেসের জন্য অপেক্ষা করা হচ্ছে · স্বয়ংক্রিয়ভাবে পরীক্ষা করা হচ্ছে",
    "repairing": "সিস্টেম সেটিংস প্রস্তুত করা হচ্ছে…",
    "openSettings": "সেটিংস খুলুন",
    "errorTitle": "ChatGPT-এর অনুমতি সেটআপ অসম্পূর্ণ",
    "errorBody": "অনুমতি সেটআপ সম্পূর্ণ করা যায়নি। সিস্টেম সেটিংস → গোপনীয়তা ও নিরাপত্তা → অ্যাক্সেসিবিলিটিতে /Applications/ChatGPT.app যোগ করুন, তারপর আবার পরীক্ষা করতে incodex install চালান।"
  },
  "bs-BA": {
    "title": "Omogući upravljanje ChatGPT skriptama",
    "installedTitle": "Ponovo omogući upravljanje ChatGPT skriptama",
    "body": "Instalacija Incodexa mijenja ChatGPT, pa se dozvola za pristupačnost mora ponovo odobriti.",
    "permissionTitle": "Pristupačnost",
    "permissionDescription": "Čitanje interfejsa aplikacija i interakcija s njima",
    "repair": "Dozvoli",
    "later": "Preskoči",
    "back": "Nazad",
    "addedTitle": "Dozvoli ChatGPT u sistemskim postavkama",
    "addedBody": "Prevucite gornju ikonu ChatGPT-a na listu pristupačnosti i uključite je. Završite svaku macOS provjeru identiteta. Pristup se provjerava automatski; ovaj prozor se zatvara kada pristup bude spreman.",
    "dragInstruction": "Prevucite ChatGPT na gornju listu da biste dozvolili pristupačnost",
    "completeInSettings": "Dovrši u sistemskim postavkama",
    "checking": "Čekanje na pristup · automatska provjera",
    "repairing": "Priprema sistemskih postavki…",
    "openSettings": "Otvori postavke",
    "errorTitle": "Postavljanje dozvole za ChatGPT nije dovršeno",
    "errorBody": "Postavljanje dozvole nije moguće dovršiti. Dodajte /Applications/ChatGPT.app u Sistemske postavke → Privatnost i sigurnost → Pristupačnost, a zatim pokrenite incodex install da ponovo provjerite."
  },
  "ca-ES": {
    "title": "Activa el control de scripts de ChatGPT",
    "installedTitle": "Torna a activar el control de scripts de ChatGPT",
    "body": "La instal·lació d’Incodex modifica ChatGPT, de manera que cal tornar a concedir-li el permís d’accessibilitat.",
    "permissionTitle": "Accessibilitat",
    "permissionDescription": "Llegeix i interactua amb les interfícies de les aplicacions",
    "repair": "Permet",
    "later": "Omet",
    "back": "Enrere",
    "addedTitle": "Permet ChatGPT a la Configuració del sistema",
    "addedBody": "Arrossega la icona de ChatGPT de dalt a la llista d’accessibilitat i activa-la. Completa qualsevol autenticació del macOS. L’accés es comprova automàticament; aquesta finestra es tanca quan l’accés està disponible.",
    "dragInstruction": "Arrossega ChatGPT a la llista de dalt per permetre l’accessibilitat",
    "completeInSettings": "Completa-ho a la Configuració del sistema",
    "checking": "Esperant l’accés · comprovació automàtica",
    "repairing": "Preparant la Configuració del sistema…",
    "openSettings": "Obre la configuració",
    "errorTitle": "La configuració dels permisos de ChatGPT no s’ha completat",
    "errorBody": "No s’ha pogut completar la configuració dels permisos. Afegeix /Applications/ChatGPT.app a Configuració del sistema → Privacitat i seguretat → Accessibilitat i, després, executa incodex install per tornar-ho a comprovar."
  },
  "cs-CZ": {
    "title": "Povolit ovládání skriptů ChatGPT",
    "installedTitle": "Znovu povolit ovládání skriptů ChatGPT",
    "body": "Instalace Incodexu upraví ChatGPT, proto je nutné znovu udělit oprávnění Zpřístupnění.",
    "permissionTitle": "Zpřístupnění",
    "permissionDescription": "Čtení rozhraní aplikací a interakce s nimi",
    "repair": "Povolit",
    "later": "Přeskočit",
    "back": "Zpět",
    "addedTitle": "Povolit ChatGPT v Nastavení systému",
    "addedBody": "Přetáhněte ikonu ChatGPT výše do seznamu Zpřístupnění a povolte ji. Dokončete případné ověření v macOS. Přístup se kontroluje automaticky; toto okno se zavře, jakmile bude přístup připraven.",
    "dragInstruction": "Přetáhněte ChatGPT do seznamu výše a povolte Zpřístupnění",
    "completeInSettings": "Dokončit v Nastavení systému",
    "checking": "Čekání na přístup · probíhá automatická kontrola",
    "repairing": "Příprava Nastavení systému…",
    "openSettings": "Otevřít Nastavení",
    "errorTitle": "Nastavení oprávnění ChatGPT není dokončené",
    "errorBody": "Nastavení oprávnění se nepodařilo dokončit. Přidejte /Applications/ChatGPT.app v Nastavení systému → Soukromí a zabezpečení → Zpřístupnění a spusťte incodex install pro novou kontrolu."
  },
  "da-DK": {
    "title": "Slå scriptstyring til for ChatGPT",
    "installedTitle": "Slå scriptstyring til for ChatGPT igen",
    "body": "Installationen af Incodex ændrer ChatGPT, så tilladelsen til Tilgængelighed skal gives igen.",
    "permissionTitle": "Tilgængelighed",
    "permissionDescription": "Læs og interager med appgrænseflader",
    "repair": "Tillad",
    "later": "Spring over",
    "back": "Tilbage",
    "addedTitle": "Tillad ChatGPT i Systemindstillinger",
    "addedBody": "Træk ChatGPT-symbolet ovenfor til listen Tilgængelighed, og slå det til. Gennemfør eventuel godkendelse i macOS. Adgangen kontrolleres automatisk; dette vindue lukkes, når adgangen er klar.",
    "dragInstruction": "Træk ChatGPT til listen ovenfor for at tillade Tilgængelighed",
    "completeInSettings": "Gør færdig i Systemindstillinger",
    "checking": "Venter på adgang · kontrollerer automatisk",
    "repairing": "Gør Systemindstillinger klar…",
    "openSettings": "Åbn indstillinger",
    "errorTitle": "ChatGPT-tilladelsen er ikke konfigureret færdig",
    "errorBody": "Tilladelsen kunne ikke konfigureres færdig. Føj /Applications/ChatGPT.app til Systemindstillinger → Anonymitet og sikkerhed → Tilgængelighed, og kør derefter incodex install for at kontrollere igen."
  },
  "de-DE": {
    "title": "ChatGPT-Skriptsteuerung aktivieren",
    "installedTitle": "ChatGPT-Skriptsteuerung erneut aktivieren",
    "body": "Die Installation von Incodex ändert ChatGPT. Daher muss die Bedienungshilfen-Berechtigung erneut erteilt werden.",
    "permissionTitle": "Bedienungshilfen",
    "permissionDescription": "App-Oberflächen lesen und mit ihnen interagieren",
    "repair": "Erlauben",
    "later": "Überspringen",
    "back": "Zurück",
    "addedTitle": "ChatGPT in den Systemeinstellungen erlauben",
    "addedBody": "Ziehe das ChatGPT-Symbol oben in die Liste der Bedienungshilfen und aktiviere es. Schließe alle macOS-Authentifizierungen ab. Der Zugriff wird automatisch geprüft; dieses Fenster wird geschlossen, sobald der Zugriff bereit ist.",
    "dragInstruction": "Ziehe ChatGPT in die Liste oben, um den Zugriff auf die Bedienungshilfen zu erlauben",
    "completeInSettings": "In den Systemeinstellungen abschließen",
    "checking": "Warten auf Zugriff · automatische Prüfung läuft",
    "repairing": "Systemeinstellungen werden vorbereitet…",
    "openSettings": "Einstellungen öffnen",
    "errorTitle": "Die Einrichtung der ChatGPT-Berechtigung ist unvollständig",
    "errorBody": "Die Einrichtung der Berechtigung konnte nicht abgeschlossen werden. Füge /Applications/ChatGPT.app in den Systemeinstellungen → Datenschutz & Sicherheit → Bedienungshilfen hinzu und führe anschließend incodex install aus, um erneut zu prüfen."
  },
  "el-GR": {
    "title": "Ενεργοποίηση ελέγχου σεναρίων του ChatGPT",
    "installedTitle": "Επανενεργοποίηση του ελέγχου σεναρίων του ChatGPT",
    "body": "Η εγκατάσταση του Incodex τροποποιεί το ChatGPT, επομένως πρέπει να παραχωρηθεί ξανά η άδεια Προσβασιμότητας.",
    "permissionTitle": "Προσβασιμότητα",
    "permissionDescription": "Ανάγνωση και αλληλεπίδραση με τις διεπαφές εφαρμογών",
    "repair": "Να επιτρέπεται",
    "later": "Παράλειψη",
    "back": "Πίσω",
    "addedTitle": "Να επιτρέπεται το ChatGPT στις Ρυθμίσεις συστήματος",
    "addedBody": "Σύρετε το εικονίδιο του ChatGPT παραπάνω στη λίστα Προσβασιμότητας και ενεργοποιήστε το. Ολοκληρώστε τυχόν έλεγχο ταυτότητας του macOS. Η πρόσβαση ελέγχεται αυτόματα· αυτό το παράθυρο κλείνει όταν η πρόσβαση είναι έτοιμη.",
    "dragInstruction": "Σύρετε το ChatGPT στην παραπάνω λίστα για να επιτρέψετε την Προσβασιμότητα",
    "completeInSettings": "Ολοκλήρωση στις Ρυθμίσεις συστήματος",
    "checking": "Αναμονή για πρόσβαση · αυτόματος έλεγχος",
    "repairing": "Προετοιμασία των Ρυθμίσεων συστήματος…",
    "openSettings": "Άνοιγμα ρυθμίσεων",
    "errorTitle": "Η ρύθμιση των δικαιωμάτων του ChatGPT δεν έχει ολοκληρωθεί",
    "errorBody": "Δεν ήταν δυνατή η ολοκλήρωση της ρύθμισης δικαιωμάτων. Προσθέστε το /Applications/ChatGPT.app στις Ρυθμίσεις συστήματος → Απόρρητο και ασφάλεια → Προσβασιμότητα και, στη συνέχεια, εκτελέστε το incodex install για νέο έλεγχο."
  },
  "es-419": {
    "title": "Activar el control de scripts de ChatGPT",
    "installedTitle": "Volver a activar el control de scripts de ChatGPT",
    "body": "La instalación de Incodex modifica ChatGPT, por lo que debes volver a concederle el permiso de Accesibilidad.",
    "permissionTitle": "Accesibilidad",
    "permissionDescription": "Leer e interactuar con las interfaces de las apps",
    "repair": "Permitir",
    "later": "Omitir",
    "back": "Atrás",
    "addedTitle": "Permitir ChatGPT en Configuración del Sistema",
    "addedBody": "Arrastra el icono de ChatGPT de arriba a la lista de Accesibilidad y actívalo. Completa cualquier autenticación de macOS. El acceso se comprueba automáticamente; esta ventana se cierra cuando el acceso está listo.",
    "dragInstruction": "Arrastra ChatGPT a la lista de arriba para permitir la Accesibilidad",
    "completeInSettings": "Completar en Configuración del Sistema",
    "checking": "Esperando acceso · comprobando automáticamente",
    "repairing": "Preparando Configuración del Sistema…",
    "openSettings": "Abrir configuración",
    "errorTitle": "La configuración de permisos de ChatGPT está incompleta",
    "errorBody": "No se pudo completar la configuración de permisos. Añade /Applications/ChatGPT.app en Configuración del Sistema → Privacidad y seguridad → Accesibilidad y luego ejecuta incodex install para volver a comprobarlo."
  },
  "es-ES": {
    "title": "Activar el control de scripts de ChatGPT",
    "installedTitle": "Volver a activar el control de scripts de ChatGPT",
    "body": "La instalación de Incodex modifica ChatGPT, por lo que debes volver a concederle el permiso de Accesibilidad.",
    "permissionTitle": "Accesibilidad",
    "permissionDescription": "Leer e interactuar con las interfaces de las aplicaciones",
    "repair": "Permitir",
    "later": "Omitir",
    "back": "Atrás",
    "addedTitle": "Permitir ChatGPT en Ajustes del Sistema",
    "addedBody": "Arrastra el icono de ChatGPT de arriba a la lista de Accesibilidad y actívalo. Completa cualquier autenticación de macOS. El acceso se comprueba automáticamente; esta ventana se cierra cuando el acceso está listo.",
    "dragInstruction": "Arrastra ChatGPT a la lista de arriba para permitir la Accesibilidad",
    "completeInSettings": "Completar en Ajustes del Sistema",
    "checking": "Esperando acceso · comprobando automáticamente",
    "repairing": "Preparando Ajustes del Sistema…",
    "openSettings": "Abrir ajustes",
    "errorTitle": "La configuración de permisos de ChatGPT está incompleta",
    "errorBody": "No se pudo completar la configuración de permisos. Añade /Applications/ChatGPT.app en Ajustes del Sistema → Privacidad y seguridad → Accesibilidad y luego ejecuta incodex install para volver a comprobarlo."
  },
  "et-EE": {
    "title": "Luba ChatGPT skriptijuhtimine",
    "installedTitle": "Luba ChatGPT skriptijuhtimine uuesti",
    "body": "Incodexi paigaldamine muudab ChatGPT-d, seega tuleb juurdepääsetavuse luba uuesti anda.",
    "permissionTitle": "Hõlbustusfunktsioonid",
    "permissionDescription": "Rakenduste liideste lugemine ja nendega suhtlemine",
    "repair": "Luba",
    "later": "Jäta vahele",
    "back": "Tagasi",
    "addedTitle": "Luba ChatGPT süsteemiseadetes",
    "addedBody": "Lohista ülal olev ChatGPT ikoon hõlbustusfunktsioonide loendisse ja luba see. Lõpeta kõik macOS-i autentimised. Juurdepääsu kontrollitakse automaatselt; see aken sulgub, kui juurdepääs on valmis.",
    "dragInstruction": "Juurdepääsetavuse lubamiseks lohista ChatGPT ülalolevasse loendisse",
    "completeInSettings": "Lõpeta süsteemiseadetes",
    "checking": "Juurdepääsu ootel · automaatne kontroll",
    "repairing": "Süsteemiseadete ettevalmistamine…",
    "openSettings": "Ava seaded",
    "errorTitle": "ChatGPT juurdepääsu seadistus pole lõpetatud",
    "errorBody": "Juurdepääsu seadistust ei saanud lõpetada. Lisa /Applications/ChatGPT.app süsteemiseadetes → Privaatsus ja turvalisus → Hõlbustusfunktsioonid ning käivita seejärel incodex install, et uuesti kontrollida."
  },
  "fa": {
    "title": "فعال‌کردن کنترل اسکریپت ChatGPT",
    "installedTitle": "فعال‌کردن دوبارهٔ کنترل اسکریپت ChatGPT",
    "body": "نصب Incodex، ChatGPT را تغییر می‌دهد؛ بنابراین باید مجوز دسترسی‌پذیری آن را دوباره بدهید.",
    "permissionTitle": "دسترسی‌پذیری",
    "permissionDescription": "خواندن و تعامل با رابط‌های برنامه‌ها",
    "repair": "اجازه دادن",
    "later": "رد شدن",
    "back": "بازگشت",
    "addedTitle": "اجازه دادن به ChatGPT در تنظیمات سیستم",
    "addedBody": "نماد ChatGPT بالا را به فهرست دسترسی‌پذیری بکشید و آن را فعال کنید. هرگونه احراز هویت macOS را کامل کنید. دسترسی به‌طور خودکار بررسی می‌شود؛ این پنجره وقتی دسترسی آماده باشد بسته می‌شود.",
    "dragInstruction": "برای اجازه دادن به دسترسی‌پذیری، ChatGPT را به فهرست بالا بکشید",
    "completeInSettings": "تکمیل در تنظیمات سیستم",
    "checking": "در انتظار دسترسی · بررسی خودکار",
    "repairing": "در حال آماده‌سازی تنظیمات سیستم…",
    "openSettings": "باز کردن تنظیمات",
    "errorTitle": "راه‌اندازی مجوز ChatGPT ناقص است",
    "errorBody": "راه‌اندازی مجوز کامل نشد. /Applications/ChatGPT.app را در تنظیمات سیستم → حریم خصوصی و امنیت → دسترسی‌پذیری اضافه کنید، سپس برای بررسی دوباره incodex install را اجرا کنید."
  },
  "fi-FI": {
    "title": "Ota ChatGPT-komentosarjaohjaus käyttöön",
    "installedTitle": "Ota ChatGPT-komentosarjaohjaus uudelleen käyttöön",
    "body": "Incodexin asentaminen muokkaa ChatGPT:tä, joten sen Käyttöapu-oikeus on myönnettävä uudelleen.",
    "permissionTitle": "Käyttöapu",
    "permissionDescription": "Lue appien käyttöliittymiä ja käytä niitä",
    "repair": "Salli",
    "later": "Ohita",
    "back": "Takaisin",
    "addedTitle": "Salli ChatGPT Järjestelmäasetuksissa",
    "addedBody": "Vedä yllä oleva ChatGPT-kuvake Käyttöapu-luetteloon ja ota se käyttöön. Suorita kaikki macOS:n edellyttämät todennukset. Käyttöoikeus tarkistetaan automaattisesti; tämä ikkuna sulkeutuu, kun käyttöoikeus on valmis.",
    "dragInstruction": "Salli Käyttöapu vetämällä ChatGPT yllä olevaan luetteloon",
    "completeInSettings": "Viimeistele Järjestelmäasetuksissa",
    "checking": "Odotetaan käyttöoikeutta · tarkistetaan automaattisesti",
    "repairing": "Valmistellaan Järjestelmäasetuksia…",
    "openSettings": "Avaa asetukset",
    "errorTitle": "ChatGPT:n käyttöoikeuden määritys on kesken",
    "errorBody": "Käyttöoikeuden määritystä ei voitu viimeistellä. Lisää /Applications/ChatGPT.app Järjestelmäasetuksissa kohtaan → Tietosuoja ja suojaus → Käyttöapu ja suorita sitten incodex install tarkistaaksesi uudelleen."
  },
  "fr-CA": {
    "title": "Activer le contrôle des scripts de ChatGPT",
    "installedTitle": "Réactiver le contrôle des scripts de ChatGPT",
    "body": "L’installation d’Incodex modifie ChatGPT; son autorisation d’accessibilité doit donc être accordée de nouveau.",
    "permissionTitle": "Accessibilité",
    "permissionDescription": "Lire les interfaces des apps et interagir avec elles",
    "repair": "Autoriser",
    "later": "Ignorer",
    "back": "Retour",
    "addedTitle": "Autoriser ChatGPT dans Réglages système",
    "addedBody": "Faites glisser l’icône de ChatGPT ci-dessus dans la liste Accessibilité et activez-la. Terminez toute authentification demandée par macOS. L’accès est vérifié automatiquement; cette fenêtre se ferme quand l’accès est prêt.",
    "dragInstruction": "Faites glisser ChatGPT dans la liste ci-dessus pour autoriser l’accessibilité",
    "completeInSettings": "Terminer dans Réglages système",
    "checking": "En attente de l’accès · vérification automatique",
    "repairing": "Préparation de Réglages système…",
    "openSettings": "Ouvrir les réglages",
    "errorTitle": "La configuration des autorisations de ChatGPT est incomplète",
    "errorBody": "La configuration des autorisations n’a pas pu être terminée. Ajoutez /Applications/ChatGPT.app dans Réglages système → Confidentialité et sécurité → Accessibilité, puis exécutez incodex install pour vérifier de nouveau."
  },
  "fr-FR": {
    "title": "Activer le contrôle des scripts de ChatGPT",
    "installedTitle": "Réactiver le contrôle des scripts de ChatGPT",
    "body": "L’installation d’Incodex modifie ChatGPT; son autorisation d’accessibilité doit donc être accordée de nouveau.",
    "permissionTitle": "Accessibilité",
    "permissionDescription": "Lire les interfaces des apps et interagir avec elles",
    "repair": "Autoriser",
    "later": "Ignorer",
    "back": "Retour",
    "addedTitle": "Autoriser ChatGPT dans Réglages Système",
    "addedBody": "Faites glisser l’icône de ChatGPT ci-dessus dans la liste Accessibilité et activez-la. Terminez toute authentification demandée par macOS. L’accès est vérifié automatiquement; cette fenêtre se ferme quand l’accès est prêt.",
    "dragInstruction": "Faites glisser ChatGPT dans la liste ci-dessus pour autoriser l’accessibilité",
    "completeInSettings": "Terminer dans Réglages Système",
    "checking": "En attente de l’accès · vérification automatique",
    "repairing": "Préparation de Réglages Système…",
    "openSettings": "Ouvrir les réglages",
    "errorTitle": "La configuration des autorisations de ChatGPT est incomplète",
    "errorBody": "La configuration des autorisations n’a pas pu être terminée. Ajoutez /Applications/ChatGPT.app dans Réglages Système → Confidentialité et sécurité → Accessibilité, puis exécutez incodex install pour vérifier de nouveau."
  },
  "gu-IN": {
    "title": "ChatGPT સ્ક્રિપ્ટ નિયંત્રણ સક્ષમ કરો",
    "installedTitle": "ChatGPT સ્ક્રિપ્ટ નિયંત્રણ ફરીથી સક્ષમ કરો",
    "body": "Incodex ઇન્સ્ટોલ કરવાથી ChatGPTમાં ફેરફાર થાય છે, તેથી તેની ઍક્સેસિબિલિટી પરવાનગી ફરીથી આપવી જરૂરી છે.",
    "permissionTitle": "ઍક્સેસિબિલિટી",
    "permissionDescription": "ઍપના ઇન્ટરફેસ વાંચો અને તેની સાથે ક્રિયા કરો",
    "repair": "મંજૂરી આપો",
    "later": "છોડી દો",
    "back": "પાછળ",
    "addedTitle": "સિસ્ટમ સેટિંગ્સમાં ChatGPTને મંજૂરી આપો",
    "addedBody": "ઉપરનું ChatGPT ચિહ્ન ઍક્સેસિબિલિટી સૂચિમાં ખેંચી લાવી તેને સક્ષમ કરો. macOS માટે જરૂરી કોઈપણ પ્રમાણીકરણ પૂર્ણ કરો. ઍક્સેસ આપમેળે તપાસવામાં આવશે; ઍક્સેસ તૈયાર થાય ત્યારે આ વિન્ડો બંધ થઈ જશે.",
    "dragInstruction": "ઍક્સેસિબિલિટી મંજૂર કરવા ChatGPTને ઉપરની સૂચિમાં ખેંચો",
    "completeInSettings": "સિસ્ટમ સેટિંગ્સમાં પૂર્ણ કરો",
    "checking": "ઍક્સેસની રાહ જોવાઈ રહી છે · આપમેળે તપાસી રહ્યું છે",
    "repairing": "સિસ્ટમ સેટિંગ્સ તૈયાર થઈ રહી છે…",
    "openSettings": "સેટિંગ્સ ખોલો",
    "errorTitle": "ChatGPTની પરવાનગી સેટઅપ અધૂરી છે",
    "errorBody": "પરવાનગી સેટઅપ પૂર્ણ કરી શકાયું નથી. /Applications/ChatGPT.app ને સિસ્ટમ સેટિંગ્સ → ગોપનીયતા અને સુરક્ષા → ઍક્સેસિબિલિટીમાં ઉમેરો, પછી ફરીથી તપાસવા incodex install ચલાવો."
  },
  "hi-IN": {
    "title": "ChatGPT स्क्रिप्ट नियंत्रण सक्षम करें",
    "installedTitle": "ChatGPT स्क्रिप्ट नियंत्रण फिर से सक्षम करें",
    "body": "Incodex इंस्टॉल करने से ChatGPT में बदलाव होता है, इसलिए इसकी ऐक्सेसिबिलिटी अनुमति फिर से देनी होगी।",
    "permissionTitle": "ऐक्सेसिबिलिटी",
    "permissionDescription": "ऐप इंटरफ़ेस पढ़ें और उनके साथ इंटरैक्ट करें",
    "repair": "अनुमति दें",
    "later": "छोड़ें",
    "back": "वापस",
    "addedTitle": "सिस्टम सेटिंग्ज़ में ChatGPT को अनुमति दें",
    "addedBody": "ऊपर दिए गए ChatGPT आइकन को ऐक्सेसिबिलिटी सूची में खींचकर लाएँ और इसे सक्षम करें। macOS के लिए आवश्यक कोई भी प्रमाणीकरण पूरा करें। ऐक्सेस अपने-आप जाँचा जाता है; ऐक्सेस तैयार होने पर यह विंडो बंद हो जाएगी।",
    "dragInstruction": "ऐक्सेसिबिलिटी की अनुमति देने के लिए ChatGPT को ऊपर दी गई सूची में खींचें",
    "completeInSettings": "सिस्टम सेटिंग्ज़ में पूरा करें",
    "checking": "ऐक्सेस की प्रतीक्षा की जा रही है · अपने-आप जाँच हो रही है",
    "repairing": "सिस्टम सेटिंग्ज़ तैयार की जा रही हैं…",
    "openSettings": "सेटिंग्ज़ खोलें",
    "errorTitle": "ChatGPT की अनुमति का सेटअप अधूरा है",
    "errorBody": "अनुमति का सेटअप पूरा नहीं किया जा सका। /Applications/ChatGPT.app को सिस्टम सेटिंग्ज़ → गोपनीयता और सुरक्षा → ऐक्सेसिबिलिटी में जोड़ें, फिर दोबारा जाँचने के लिए incodex install चलाएँ।"
  },
  "hr-HR": {
    "title": "Omogući upravljanje ChatGPT skriptama",
    "installedTitle": "Ponovno omogući upravljanje ChatGPT skriptama",
    "body": "Instalacija Incodexa mijenja ChatGPT pa se dozvola za pristupačnost mora ponovno dodijeliti.",
    "permissionTitle": "Pristupačnost",
    "permissionDescription": "Čitaj sučelja aplikacija i stupaj u interakciju s njima",
    "repair": "Dopusti",
    "later": "Preskoči",
    "back": "Natrag",
    "addedTitle": "Dopusti ChatGPT u Postavkama sustava",
    "addedBody": "Povucite gornju ikonu ChatGPT-a na popis pristupačnosti i uključite je. Dovršite svaku macOS provjeru autentičnosti. Pristup se provjerava automatski; ovaj će se prozor zatvoriti kada pristup bude spreman.",
    "dragInstruction": "Povucite ChatGPT na gornji popis da biste dopustili pristupačnost",
    "completeInSettings": "Dovrši u Postavkama sustava",
    "checking": "Čekanje pristupa · automatska provjera",
    "repairing": "Priprema Postavki sustava…",
    "openSettings": "Otvori postavke",
    "errorTitle": "Postavljanje dozvole za ChatGPT nije dovršeno",
    "errorBody": "Postavljanje dozvole nije moguće dovršiti. Dodajte /Applications/ChatGPT.app u Postavke sustava → Privatnost i sigurnost → Pristupačnost, a zatim pokrenite incodex install za ponovnu provjeru."
  },
  "hu-HU": {
    "title": "A ChatGPT szkriptvezérlésének engedélyezése",
    "installedTitle": "A ChatGPT szkriptvezérlésének újbóli engedélyezése",
    "body": "Az Incodex telepítése módosítja a ChatGPT-t, ezért újra meg kell adni neki a Kisegítő lehetőségek engedélyét.",
    "permissionTitle": "Kisegítő lehetőségek",
    "permissionDescription": "Az alkalmazások felületeinek olvasása és kezelése",
    "repair": "Engedélyezés",
    "later": "Kihagyás",
    "back": "Vissza",
    "addedTitle": "A ChatGPT engedélyezése a Rendszerbeállításokban",
    "addedBody": "Húzza a fenti ChatGPT-ikont a Kisegítő lehetőségek listájára, és engedélyezze. Végezze el a macOS által kért hitelesítést. A hozzáférést a rendszer automatikusan ellenőrzi; ez az ablak bezárul, amikor a hozzáférés elérhető.",
    "dragInstruction": "Húzza a ChatGPT-t a fenti listára a Kisegítő lehetőségek engedélyezéséhez",
    "completeInSettings": "Befejezés a Rendszerbeállításokban",
    "checking": "Hozzáférésre várakozás · automatikus ellenőrzés",
    "repairing": "A Rendszerbeállítások előkészítése…",
    "openSettings": "Beállítások megnyitása",
    "errorTitle": "A ChatGPT engedélyeinek beállítása nem teljes",
    "errorBody": "Az engedélyek beállítását nem sikerült befejezni. Adja hozzá a /Applications/ChatGPT.app fájlt a Rendszerbeállítások → Adatvédelem és biztonság → Kisegítő lehetőségek részéhez, majd futtassa az incodex install parancsot az újbóli ellenőrzéshez."
  },
  "hy-AM": {
    "title": "Միացնել ChatGPT-ի սկրիպտերի կառավարումը",
    "installedTitle": "Կրկին միացնել ChatGPT-ի սկրիպտերի կառավարումը",
    "body": "Incodex-ի տեղադրումը փոփոխում է ChatGPT-ը, ուստի Մատչելիության թույլտվությունը պետք է կրկին տրամադրել։",
    "permissionTitle": "Մատչելիություն",
    "permissionDescription": "Կարդալ և փոխազդել հավելվածների միջերեսների հետ",
    "repair": "Թույլատրել",
    "later": "Բաց թողնել",
    "back": "Հետ",
    "addedTitle": "Թույլատրել ChatGPT-ին Համակարգի կարգավորումներում",
    "addedBody": "Վերևում գտնվող ChatGPT-ի պատկերակը քաշեք Մատչելիության ցանկ և միացրեք այն։ Կատարեք macOS-ի պահանջած նույնականացումը։ Մուտքը ստուգվում է ավտոմատ կերպով. այս պատուհանը կփակվի, երբ մուտքը պատրաստ լինի։",
    "dragInstruction": "Մատչելիությունը թույլատրելու համար ChatGPT-ը քաշեք վերևի ցանկ",
    "completeInSettings": "Ավարտել Համակարգի կարգավորումներում",
    "checking": "Սպասում ենք մուտքին · ավտոմատ ստուգում",
    "repairing": "Համակարգի կարգավորումների նախապատրաստում…",
    "openSettings": "Բացել կարգավորումները",
    "errorTitle": "ChatGPT-ի թույլտվությունների կարգավորումն ավարտված չէ",
    "errorBody": "Թույլտվությունների կարգավորումն ավարտել չհաջողվեց։ /Applications/ChatGPT.app ավելացրեք Համակարգի կարգավորումներ → Գաղտնիություն և անվտանգություն → Մատչելիություն բաժնում, ապա կրկին ստուգելու համար գործարկեք incodex install։"
  },
  "id-ID": {
    "title": "Aktifkan kontrol skrip ChatGPT",
    "installedTitle": "Aktifkan kembali kontrol skrip ChatGPT",
    "body": "Instalasi Incodex mengubah ChatGPT, jadi izin Aksesibilitasnya perlu diberikan lagi.",
    "permissionTitle": "Aksesibilitas",
    "permissionDescription": "Membaca dan berinteraksi dengan antarmuka app",
    "repair": "Izinkan",
    "later": "Lewati",
    "back": "Kembali",
    "addedTitle": "Izinkan ChatGPT di Pengaturan Sistem",
    "addedBody": "Seret ikon ChatGPT di atas ke daftar Aksesibilitas, lalu aktifkan. Selesaikan autentikasi macOS jika diminta. Akses diperiksa secara otomatis; jendela ini akan tertutup saat akses siap.",
    "dragInstruction": "Seret ChatGPT ke daftar di atas untuk mengizinkan Aksesibilitas",
    "completeInSettings": "Selesaikan di Pengaturan Sistem",
    "checking": "Menunggu akses · memeriksa secara otomatis",
    "repairing": "Menyiapkan Pengaturan Sistem…",
    "openSettings": "Buka Pengaturan",
    "errorTitle": "Penyiapan izin ChatGPT belum selesai",
    "errorBody": "Penyiapan izin tidak dapat diselesaikan. Tambahkan /Applications/ChatGPT.app di Pengaturan Sistem → Privasi & Keamanan → Aksesibilitas, lalu jalankan incodex install untuk memeriksa lagi."
  },
  "is-IS": {
    "title": "Kveiktu á skriftustýringu ChatGPT",
    "installedTitle": "Kveiktu aftur á skriftustýringu ChatGPT",
    "body": "Uppsetning Incodex breytir ChatGPT, þannig að veita þarf aðgengisheimild þess aftur.",
    "permissionTitle": "Aðgengi",
    "permissionDescription": "Lesa og eiga samskipti við notendaviðmót forrita",
    "repair": "Leyfa",
    "later": "Sleppa",
    "back": "Til baka",
    "addedTitle": "Leyfa ChatGPT í Kerfisstillingum",
    "addedBody": "Dragðu ChatGPT-táknið hér að ofan yfir á aðgengislistann og virkjaðu það. Ljúktu öllum auðkenningum sem macOS krefst. Aðgangur er kannaður sjálfkrafa; þessi gluggi lokast þegar aðgangur er tilbúinn.",
    "dragInstruction": "Dragðu ChatGPT á listann hér að ofan til að leyfa aðgengi",
    "completeInSettings": "Ljúka í Kerfisstillingum",
    "checking": "Bíð eftir aðgangi · kannar sjálfkrafa",
    "repairing": "Undirbý Kerfisstillingar…",
    "openSettings": "Opna stillingar",
    "errorTitle": "Uppsetningu ChatGPT-heimilda er ekki lokið",
    "errorBody": "Ekki tókst að ljúka uppsetningu heimilda. Bættu /Applications/ChatGPT.app við í Kerfisstillingum → Persónuvernd og öryggi → Aðgengi og keyrðu síðan incodex install til að kanna aftur."
  },
  "it-IT": {
    "title": "Abilita il controllo degli script di ChatGPT",
    "installedTitle": "Riattiva il controllo degli script di ChatGPT",
    "body": "L’installazione di Incodex modifica ChatGPT, quindi è necessario concedere di nuovo l’autorizzazione Accessibilità.",
    "permissionTitle": "Accessibilità",
    "permissionDescription": "Leggere e interagire con le interfacce delle app",
    "repair": "Consenti",
    "later": "Salta",
    "back": "Indietro",
    "addedTitle": "Consenti ChatGPT nelle Impostazioni di Sistema",
    "addedBody": "Trascina l’icona di ChatGPT qui sopra nell’elenco Accessibilità e abilitala. Completa tutte le autenticazioni richieste da macOS. L’accesso viene verificato automaticamente; questa finestra si chiude quando l’accesso è pronto.",
    "dragInstruction": "Trascina ChatGPT nell’elenco qui sopra per consentire l’accesso all’Accessibilità",
    "completeInSettings": "Completa nelle Impostazioni di Sistema",
    "checking": "In attesa dell’accesso · verifica automatica",
    "repairing": "Preparazione delle Impostazioni di Sistema…",
    "openSettings": "Apri impostazioni",
    "errorTitle": "La configurazione delle autorizzazioni di ChatGPT non è completa",
    "errorBody": "Non è stato possibile completare la configurazione delle autorizzazioni. Aggiungi /Applications/ChatGPT.app in Impostazioni di Sistema → Privacy e sicurezza → Accessibilità, quindi esegui incodex install per verificare di nuovo."
  },
  "ja-JP": {
    "title": "ChatGPT のスクリプト制御を有効にする",
    "installedTitle": "ChatGPT のスクリプト制御を再び有効にする",
    "body": "Incodex をインストールすると ChatGPT が変更されるため、アクセシビリティの許可をもう一度与える必要があります。",
    "permissionTitle": "アクセシビリティ",
    "permissionDescription": "アプリのインターフェイスを読み取り、操作する",
    "repair": "許可",
    "later": "スキップ",
    "back": "戻る",
    "addedTitle": "システム設定で ChatGPT を許可",
    "addedBody": "上の ChatGPT アイコンをアクセシビリティのリストにドラッグして有効にします。macOS が求める認証を完了してください。アクセスは自動的に確認され、使用できるようになるとこのウインドウが閉じます。",
    "dragInstruction": "アクセシビリティを許可するには、ChatGPT を上のリストにドラッグします",
    "completeInSettings": "システム設定で完了",
    "checking": "アクセスを待機中 · 自動的に確認しています",
    "repairing": "システム設定を準備中…",
    "openSettings": "設定を開く",
    "errorTitle": "ChatGPT のアクセス許可設定が完了していません",
    "errorBody": "アクセス許可設定を完了できませんでした。システム設定 → プライバシーとセキュリティ → アクセシビリティで /Applications/ChatGPT.app を追加し、再度確認するために incodex install を実行してください。"
  },
  "ka-GE": {
    "title": "ChatGPT-ის სკრიპტების მართვის ჩართვა",
    "installedTitle": "ChatGPT-ის სკრიპტების მართვის ხელახლა ჩართვა",
    "body": "Incodex-ის ინსტალაცია ChatGPT-ს ცვლის, ამიტომ წვდომადობის ნებართვა ხელახლა უნდა მიენიჭოს.",
    "permissionTitle": "წვდომადობა",
    "permissionDescription": "აპების ინტერფეისების წაკითხვა და მათთან ურთიერთქმედება",
    "repair": "დაშვება",
    "later": "გამოტოვება",
    "back": "უკან",
    "addedTitle": "ChatGPT-ის დაშვება სისტემის პარამეტრებში",
    "addedBody": "ზემოთ მოცემული ChatGPT-ის ხატულა გადაათრიეთ წვდომადობის სიაში და ჩართეთ. შეასრულეთ macOS-ის ნებისმიერი მოთხოვნილი ავთენტიფიკაცია. წვდომა ავტომატურად შემოწმდება; ეს ფანჯარა დაიხურება, როცა წვდომა მზად იქნება.",
    "dragInstruction": "წვდომადობის დასაშვებად ChatGPT ზემოთ მოცემულ სიაში გადაათრიეთ",
    "completeInSettings": "დასრულება სისტემის პარამეტრებში",
    "checking": "წვდომის მოლოდინი · ავტომატური შემოწმება",
    "repairing": "სისტემის პარამეტრების მომზადება…",
    "openSettings": "პარამეტრების გახსნა",
    "errorTitle": "ChatGPT-ის ნებართვების დაყენება არასრულია",
    "errorBody": "ნებართვების დაყენება ვერ დასრულდა. /Applications/ChatGPT.app დაამატეთ სისტემის პარამეტრებში → კონფიდენციალურობა და უსაფრთხოება → წვდომადობა, შემდეგ ხელახლა შესამოწმებლად გაუშვით incodex install."
  },
  "kk": {
    "title": "ChatGPT скрипттерін басқаруды қосу",
    "installedTitle": "ChatGPT скрипттерін басқаруды қайта қосу",
    "body": "Incodex орнатылғанда ChatGPT өзгертіледі, сондықтан оның Арнайы мүмкіндіктер рұқсатын қайта беру керек.",
    "permissionTitle": "Арнайы мүмкіндіктер",
    "permissionDescription": "Қолданба интерфейстерін оқу және олармен әрекеттесу",
    "repair": "Рұқсат ету",
    "later": "Өткізіп жіберу",
    "back": "Артқа",
    "addedTitle": "Жүйе параметрлерінде ChatGPT-ке рұқсат беру",
    "addedBody": "Жоғарыдағы ChatGPT белгішесін Арнайы мүмкіндіктер тізіміне сүйреп апарып, оны қосыңыз. macOS сұраған кез келген аутентификацияны аяқтаңыз. Қолжетімділік автоматты түрде тексеріледі; қолжетімділік дайын болғанда бұл терезе жабылады.",
    "dragInstruction": "Арнайы мүмкіндіктерге рұқсат беру үшін ChatGPT-ті жоғарыдағы тізімге сүйреп апарыңыз",
    "completeInSettings": "Жүйе параметрлерінде аяқтау",
    "checking": "Қолжетімділік күтілуде · автоматты тексеру",
    "repairing": "Жүйе параметрлері дайындалуда…",
    "openSettings": "Параметрлерді ашу",
    "errorTitle": "ChatGPT рұқсатын орнату аяқталмаған",
    "errorBody": "Рұқсатты орнату аяқталмады. /Applications/ChatGPT.app қолданбасын Жүйе параметрлері → Құпиялық және қауіпсіздік → Арнайы мүмкіндіктер бөліміне қосып, қайта тексеру үшін incodex install пәрменін іске қосыңыз."
  },
  "kn-IN": {
    "title": "ChatGPT ಸ್ಕ್ರಿಪ್ಟ್ ನಿಯಂತ್ರಣವನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ",
    "installedTitle": "ChatGPT ಸ್ಕ್ರಿಪ್ಟ್ ನಿಯಂತ್ರಣವನ್ನು ಮತ್ತೆ ಸಕ್ರಿಯಗೊಳಿಸಿ",
    "body": "Incodex ಅನ್ನು ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡುವುದರಿಂದ ChatGPT ಬದಲಾಗುತ್ತದೆ, ಆದ್ದರಿಂದ ಅದರ ಆಕ್ಸೆಸಿಬಿಲಿಟಿ ಅನುಮತಿಯನ್ನು ಮತ್ತೆ ನೀಡಬೇಕು.",
    "permissionTitle": "ಆಕ್ಸೆಸಿಬಿಲಿಟಿ",
    "permissionDescription": "ಆ್ಯಪ್ ಇಂಟರ್‌ಫೇಸ್‌ಗಳನ್ನು ಓದಿ ಅವುಗಳೊಂದಿಗೆ ಸಂವಹನ ನಡೆಸಿ",
    "repair": "ಅನುಮತಿಸಿ",
    "later": "ಬಿಟ್ಟುಬಿಡಿ",
    "back": "ಹಿಂದಕ್ಕೆ",
    "addedTitle": "ಸಿಸ್ಟಂ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ChatGPTಗೆ ಅನುಮತಿಸಿ",
    "addedBody": "ಮೇಲಿನ ChatGPT ಐಕಾನ್ ಅನ್ನು ಆಕ್ಸೆಸಿಬಿಲಿಟಿ ಪಟ್ಟಿಗೆ ಎಳೆದು ತಂದು ಸಕ್ರಿಯಗೊಳಿಸಿ. macOS ಕೇಳುವ ಯಾವುದೇ ದೃಢೀಕರಣವನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ. ಪ್ರವೇಶವನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ; ಪ್ರವೇಶ ಸಿದ್ಧವಾದಾಗ ಈ ವಿಂಡೋ ಮುಚ್ಚುತ್ತದೆ.",
    "dragInstruction": "ಆಕ್ಸೆಸಿಬಿಲಿಟಿಗೆ ಅನುಮತಿಸಲು ChatGPT ಅನ್ನು ಮೇಲಿನ ಪಟ್ಟಿಗೆ ಎಳೆಯಿರಿ",
    "completeInSettings": "ಸಿಸ್ಟಂ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಪೂರ್ಣಗೊಳಿಸಿ",
    "checking": "ಪ್ರವೇಶಕ್ಕಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ · ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ",
    "repairing": "ಸಿಸ್ಟಂ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ…",
    "openSettings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ತೆರೆಯಿರಿ",
    "errorTitle": "ChatGPT ಅನುಮತಿ ಸೆಟಪ್ ಅಪೂರ್ಣವಾಗಿದೆ",
    "errorBody": "ಅನುಮತಿ ಸೆಟಪ್ ಪೂರ್ಣಗೊಳಿಸಲಾಗಲಿಲ್ಲ. /Applications/ChatGPT.app ಅನ್ನು ಸಿಸ್ಟಂ ಸೆಟ್ಟಿಂಗ್‌ಗಳು → ಗೌಪ್ಯತೆ ಮತ್ತು ಭದ್ರತೆ → ಆಕ್ಸೆಸಿಬಿಲಿಟಿಗೆ ಸೇರಿಸಿ, ನಂತರ ಮತ್ತೆ ಪರಿಶೀಲಿಸಲು incodex install ಅನ್ನು ಚಲಾಯಿಸಿ."
  },
  "ko-KR": {
    "title": "ChatGPT 스크립트 제어 활성화",
    "installedTitle": "ChatGPT 스크립트 제어 다시 활성화",
    "body": "Incodex를 설치하면 ChatGPT가 수정되므로 손쉬운 사용 권한을 다시 허용해야 합니다.",
    "permissionTitle": "손쉬운 사용",
    "permissionDescription": "앱 인터페이스를 읽고 조작하기",
    "repair": "허용",
    "later": "건너뛰기",
    "back": "뒤로",
    "addedTitle": "시스템 설정에서 ChatGPT 허용",
    "addedBody": "위의 ChatGPT 아이콘을 손쉬운 사용 목록으로 드래그하여 활성화하세요. macOS에서 요구하는 인증을 완료하세요. 접근 권한은 자동으로 확인되며, 권한이 준비되면 이 창이 닫힙니다.",
    "dragInstruction": "손쉬운 사용을 허용하려면 ChatGPT를 위 목록으로 드래그하세요",
    "completeInSettings": "시스템 설정에서 완료",
    "checking": "접근 권한을 기다리는 중 · 자동으로 확인하는 중",
    "repairing": "시스템 설정 준비 중…",
    "openSettings": "설정 열기",
    "errorTitle": "ChatGPT 권한 설정이 완료되지 않았습니다",
    "errorBody": "권한 설정을 완료하지 못했습니다. 시스템 설정 → 개인정보 보호 및 보안 → 손쉬운 사용에서 /Applications/ChatGPT.app을 추가한 다음, 다시 확인하려면 incodex install을 실행하세요."
  },
  "lt": {
    "title": "Įjungti ChatGPT scenarijų valdymą",
    "installedTitle": "Iš naujo įjungti ChatGPT scenarijų valdymą",
    "body": "Įdiegus Incodex pakeičiamas ChatGPT, todėl jo Prieinamumo leidimą reikia suteikti iš naujo.",
    "permissionTitle": "Prieinamumas",
    "permissionDescription": "Skaityti programų sąsajas ir su jomis sąveikauti",
    "repair": "Leisti",
    "later": "Praleisti",
    "back": "Atgal",
    "addedTitle": "Leisti ChatGPT sistemos nustatymuose",
    "addedBody": "Nuvilkite aukščiau esančią ChatGPT piktogramą į Prieinamumo sąrašą ir ją įjunkite. Užbaikite bet kokį macOS autentifikavimą. Prieiga tikrinama automatiškai; šis langas užsidarys, kai prieiga bus parengta.",
    "dragInstruction": "Nuvilkite ChatGPT į aukščiau esantį sąrašą, kad leistumėte Prieinamumą",
    "completeInSettings": "UŽBAIGTI SISTEMOS NUSTATYMUOSE",
    "checking": "Laukiama prieigos · tikrinama automatiškai",
    "repairing": "Ruošiami sistemos nustatymai…",
    "openSettings": "Atidaryti nustatymus",
    "errorTitle": "ChatGPT leidimo nustatymas nebaigtas",
    "errorBody": "Nepavyko užbaigti leidimo nustatymo. Sistemos nustatymuose → Privatumas ir sauga → Prieinamumas pridėkite /Applications/ChatGPT.app, tada paleiskite incodex install, kad patikrintumėte dar kartą."
  },
  "lv-LV": {
    "title": "Iespējot ChatGPT skriptu vadību",
    "installedTitle": "Atkārtoti iespējot ChatGPT skriptu vadību",
    "body": "Instalējot Incodex, ChatGPT tiek pārveidots, tāpēc tā pieejamības atļauja ir jāpiešķir vēlreiz.",
    "permissionTitle": "Pieejamība",
    "permissionDescription": "Lasīt lietotņu saskarnes un ar tām mijiedarboties",
    "repair": "Atļaut",
    "later": "Izlaist",
    "back": "Atpakaļ",
    "addedTitle": "Atļaut ChatGPT sistēmas iestatījumos",
    "addedBody": "Velciet iepriekš redzamo ChatGPT ikonu uz pieejamības sarakstu un iespējojiet to. Pabeidziet jebkuru macOS autentifikāciju. Piekļuve tiek pārbaudīta automātiski; šis logs tiks aizvērts, kad piekļuve būs gatava.",
    "dragInstruction": "Velciet ChatGPT uz iepriekš redzamo sarakstu, lai atļautu pieejamību",
    "completeInSettings": "PABEIGT SISTĒMAS IESTATĪJUMOS",
    "checking": "Gaida piekļuvi · tiek pārbaudīta automātiski",
    "repairing": "Sistēmas iestatījumu sagatavošana…",
    "openSettings": "Atvērt iestatījumus",
    "errorTitle": "ChatGPT atļauju iestatīšana nav pabeigta",
    "errorBody": "Neizdevās pabeigt atļauju iestatīšanu. Sistēmas iestatījumos → Privātums un drošība → Pieejamība pievienojiet /Applications/ChatGPT.app, pēc tam palaidiet incodex install, lai pārbaudītu vēlreiz."
  },
  "mk-MK": {
    "title": "Вклучете ја контролата на скрипти за ChatGPT",
    "installedTitle": "Вклучете ја повторно контролата на скрипти за ChatGPT",
    "body": "Инсталирањето на Incodex го менува ChatGPT, па дозволата за Пристапност треба да се додели повторно.",
    "permissionTitle": "Пристапност",
    "permissionDescription": "Читање и интеракција со интерфејсите на апликациите",
    "repair": "Дозволи",
    "later": "Прескокни",
    "back": "Назад",
    "addedTitle": "Дозволете ChatGPT во системските поставки",
    "addedBody": "Повлечете ја иконата ChatGPT погоре во списокот Пристапност и овозможете ја. Завршете ја секоја автентикација на macOS. Пристапот се проверува автоматски; овој прозорец ќе се затвори кога пристапот ќе биде подготвен.",
    "dragInstruction": "Повлечете го ChatGPT во списокот погоре за да дозволите Пристапност",
    "completeInSettings": "ЗАВРШЕТЕ ВО СИСТЕМСКИТЕ ПОСТАВКИ",
    "checking": "Се чека пристап · проверката е автоматска",
    "repairing": "Се подготвуваат системските поставки…",
    "openSettings": "Отвори поставки",
    "errorTitle": "Поставувањето на дозволата за ChatGPT не е завршено",
    "errorBody": "Поставувањето на дозволата не можеше да се заврши. Додајте /Applications/ChatGPT.app во Системски поставки → Приватност и безбедност → Пристапност, потоа извршете incodex install за повторна проверка."
  },
  "ml": {
    "title": "ChatGPT സ്ക്രിപ്റ്റ് നിയന്ത്രണം പ്രവർത്തനക്ഷമമാക്കുക",
    "installedTitle": "ChatGPT സ്ക്രിപ്റ്റ് നിയന്ത്രണം വീണ്ടും പ്രവർത്തനക്ഷമമാക്കുക",
    "body": "Incodex ഇൻസ്റ്റാൾ ചെയ്യുന്നത് ChatGPT-ൽ മാറ്റങ്ങൾ വരുത്തുന്നതിനാൽ, അതിന്റെ ആക്‌സസിബിലിറ്റി അനുമതി വീണ്ടും നൽകണം.",
    "permissionTitle": "ആക്‌സസിബിലിറ്റി",
    "permissionDescription": "ആപ്പുകളുടെ ഇന്റർഫേസുകൾ വായിക്കുകയും അവയുമായി ഇടപഴകുകയും ചെയ്യുക",
    "repair": "അനുവദിക്കുക",
    "later": "ഒഴിവാക്കുക",
    "back": "പിന്നിലേക്ക്",
    "addedTitle": "സിസ്റ്റം ക്രമീകരണങ്ങളിൽ ChatGPT അനുവദിക്കുക",
    "addedBody": "മുകളിലുള്ള ChatGPT ഐക്കൺ ആക്‌സസിബിലിറ്റി പട്ടികയിലേക്ക് വലിച്ചിട്ട് അത് പ്രവർത്തനക്ഷമമാക്കുക. macOS ആവശ്യപ്പെടുന്ന ഏതെങ്കിലും പ്രാമാണീകരണം പൂർത്തിയാക്കുക. ആക്‌സസ് സ്വയമേവ പരിശോധിക്കും; ആക്‌സസ് തയ്യാറാകുമ്പോൾ ഈ വിൻഡോ അടയും.",
    "dragInstruction": "ആക്‌സസിബിലിറ്റി അനുവദിക്കാൻ ChatGPT മുകളിലുള്ള പട്ടികയിലേക്ക് വലിച്ചിടുക",
    "completeInSettings": "സിസ്റ്റം ക്രമീകരണങ്ങളിൽ പൂർത്തിയാക്കുക",
    "checking": "ആക്‌സസിനായി കാത്തിരിക്കുന്നു · സ്വയമേവ പരിശോധിക്കുന്നു",
    "repairing": "സിസ്റ്റം ക്രമീകരണങ്ങൾ തയ്യാറാക്കുന്നു…",
    "openSettings": "ക്രമീകരണങ്ങൾ തുറക്കുക",
    "errorTitle": "ChatGPT അനുമതി സജ്ജീകരണം പൂർത്തിയായിട്ടില്ല",
    "errorBody": "അനുമതി സജ്ജീകരണം പൂർത്തിയാക്കാനായില്ല. സിസ്റ്റം ക്രമീകരണങ്ങൾ → സ്വകാര്യതയും സുരക്ഷയും → ആക്‌സസിബിലിറ്റി എന്നതിൽ /Applications/ChatGPT.app ചേർക്കുക, തുടർന്ന് വീണ്ടും പരിശോധിക്കാൻ incodex install പ്രവർത്തിപ്പിക്കുക."
  },
  "mn": {
    "title": "ChatGPT скриптийн удирдлагыг идэвхжүүлэх",
    "installedTitle": "ChatGPT скриптийн удирдлагыг дахин идэвхжүүлэх",
    "body": "Incodex суулгаснаар ChatGPT-д өөрчлөлт ордог тул түүний Хандалтын зөвшөөрлийг дахин олгоно.",
    "permissionTitle": "Хандалт",
    "permissionDescription": "Аппын интерфэйсийг уншиж, харилцах",
    "repair": "Зөвшөөрөх",
    "later": "Алгасах",
    "back": "Буцах",
    "addedTitle": "Системийн тохиргоонд ChatGPT-д зөвшөөрөл олгох",
    "addedBody": "Дээрх ChatGPT дүрсийг Хандалтын жагсаалт руу чирж оруулаад идэвхжүүлнэ үү. macOS-ийн шаардсан баталгаажуулалтыг дуусгана уу. Хандалтыг автоматаар шалгана; хандалт бэлэн болмогц энэ цонх хаагдана.",
    "dragInstruction": "Хандалт зөвшөөрөхийн тулд ChatGPT-г дээрх жагсаалт руу чирнэ үү",
    "completeInSettings": "СИСТЕМИЙН ТОХИРГООНД ДУУСГАХ",
    "checking": "Хандалтыг хүлээж байна · автоматаар шалгаж байна",
    "repairing": "Системийн тохиргоог бэлдэж байна…",
    "openSettings": "Тохиргоог нээх",
    "errorTitle": "ChatGPT-ийн зөвшөөрлийн тохиргоо дуусаагүй",
    "errorBody": "Зөвшөөрлийн тохиргоог дуусгаж чадсангүй. Системийн тохиргоо → Нууцлал ба аюулгүй байдал → Хандалт хэсэгт /Applications/ChatGPT.app нэмээд, дахин шалгахын тулд incodex install ажиллуулна уу."
  },
  "mr-IN": {
    "title": "ChatGPT स्क्रिप्ट नियंत्रण सुरू करा",
    "installedTitle": "ChatGPT स्क्रिप्ट नियंत्रण पुन्हा सुरू करा",
    "body": "Incodex इंस्टॉल केल्याने ChatGPT मध्ये बदल होतात, त्यामुळे त्याची सुलभता परवानगी पुन्हा द्यावी लागेल.",
    "permissionTitle": "सुलभता",
    "permissionDescription": "अॅपचे इंटरफेस वाचा आणि त्यांच्याशी संवाद साधा",
    "repair": "परवानगी द्या",
    "later": "वगळा",
    "back": "मागे",
    "addedTitle": "सिस्टम सेटिंग्जमध्ये ChatGPT ला परवानगी द्या",
    "addedBody": "वरील ChatGPT चिन्ह सुलभता सूचीमध्ये ड्रॅग करा आणि ते सक्षम करा. macOS प्रमाणीकरण पूर्ण करा. प्रवेश आपोआप तपासला जातो; प्रवेश तयार झाल्यावर ही विंडो बंद होईल.",
    "dragInstruction": "सुलभतेला परवानगी देण्यासाठी ChatGPT वरील सूचीमध्ये ड्रॅग करा",
    "completeInSettings": "सिस्टम सेटिंग्जमध्ये पूर्ण करा",
    "checking": "प्रवेशाची प्रतीक्षा · आपोआप तपासत आहे",
    "repairing": "सिस्टम सेटिंग्ज तयार करत आहे…",
    "openSettings": "सेटिंग्ज उघडा",
    "errorTitle": "ChatGPT परवानगी सेटअप अपूर्ण आहे",
    "errorBody": "परवानगी सेटअप पूर्ण करता आला नाही. सिस्टम सेटिंग्ज → गोपनीयता आणि सुरक्षा → सुलभता येथे /Applications/ChatGPT.app जोडा, नंतर पुन्हा तपासण्यासाठी incodex install चालवा."
  },
  "ms-MY": {
    "title": "Dayakan kawalan skrip ChatGPT",
    "installedTitle": "Dayakan semula kawalan skrip ChatGPT",
    "body": "Memasang Incodex mengubah suai ChatGPT, jadi kebenaran Kebolehcapaian perlu diberikan semula.",
    "permissionTitle": "Kebolehcapaian",
    "permissionDescription": "Baca dan berinteraksi dengan antara muka app",
    "repair": "Benarkan",
    "later": "Langkau",
    "back": "Kembali",
    "addedTitle": "Benarkan ChatGPT dalam Tetapan Sistem",
    "addedBody": "Seret ikon ChatGPT di atas ke senarai Kebolehcapaian dan dayakannya. Lengkapkan sebarang pengesahan macOS. Akses diperiksa secara automatik; tetingkap ini akan ditutup apabila akses sedia.",
    "dragInstruction": "Seret ChatGPT ke senarai di atas untuk membenarkan Kebolehcapaian",
    "completeInSettings": "LENGKAPKAN DALAM TETAPAN SISTEM",
    "checking": "Menunggu akses · menyemak secara automatik",
    "repairing": "Menyediakan Tetapan Sistem…",
    "openSettings": "Buka Tetapan",
    "errorTitle": "Persediaan kebenaran ChatGPT tidak lengkap",
    "errorBody": "Persediaan kebenaran tidak dapat diselesaikan. Tambah /Applications/ChatGPT.app dalam Tetapan Sistem → Privasi & Keselamatan → Kebolehcapaian, kemudian jalankan incodex install untuk menyemak semula."
  },
  "my-MM": {
    "title": "ChatGPT စခရစ်ထိန်းချုပ်မှုကို ဖွင့်ရန်",
    "installedTitle": "ChatGPT စခရစ်ထိန်းချုပ်မှုကို ထပ်မံဖွင့်ရန်",
    "body": "Incodex ကို ထည့်သွင်းခြင်းကြောင့် ChatGPT ကို ပြင်ဆင်မည်ဖြစ်သဖြင့် ၎င်း၏ အသုံးပြုနိုင်မှု ခွင့်ပြုချက်ကို ထပ်မံပေးရပါမည်။",
    "permissionTitle": "အသုံးပြုနိုင်မှု",
    "permissionDescription": "အက်ပ်အင်တာဖေ့စ်များကို ဖတ်ရှုပြီး အပြန်အလှန်လုပ်ဆောင်ရန်",
    "repair": "ခွင့်ပြုရန်",
    "later": "ကျော်ရန်",
    "back": "နောက်သို့",
    "addedTitle": "စနစ်ဆက်တင်များတွင် ChatGPT ကို ခွင့်ပြုရန်",
    "addedBody": "အပေါ်ရှိ ChatGPT အိုင်ကွန်ကို အသုံးပြုနိုင်မှုစာရင်းထဲသို့ ဆွဲချပြီး ဖွင့်ပါ။ macOS ၏ မည်သည့်အထောက်အထားအတည်ပြုမှုမဆို ပြီးစီးပါစေ။ အသုံးပြုခွင့်ကို အလိုအလျောက် စစ်ဆေးမည်ဖြစ်ပြီး အသုံးပြုခွင့်အဆင်သင့်ဖြစ်သောအခါ ဤဝင်းဒိုးပိတ်သွားမည်။",
    "dragInstruction": "အသုံးပြုနိုင်မှုကို ခွင့်ပြုရန် ChatGPT ကို အပေါ်ရှိစာရင်းထဲသို့ ဆွဲချပါ",
    "completeInSettings": "စနစ်ဆက်တင်များတွင် ပြီးစီးပါ",
    "checking": "အသုံးပြုခွင့်ကို စောင့်နေသည် · အလိုအလျောက် စစ်ဆေးနေသည်",
    "repairing": "စနစ်ဆက်တင်များကို ပြင်ဆင်နေသည်…",
    "openSettings": "ဆက်တင်များကို ဖွင့်ရန်",
    "errorTitle": "ChatGPT ခွင့်ပြုချက်တပ်ဆင်မှု မပြီးစီးသေးပါ",
    "errorBody": "ခွင့်ပြုချက်တပ်ဆင်မှု မပြီးစီးနိုင်ပါ။ စနစ်ဆက်တင်များ → ကိုယ်ရေးအချက်အလက်နှင့် လုံခြုံရေး → အသုံးပြုနိုင်မှု တွင် /Applications/ChatGPT.app ကို ထည့်ပြီး ထပ်မံစစ်ဆေးရန် incodex install ကို လုပ်ဆောင်ပါ။"
  },
  "nb-NO": {
    "title": "Aktiver skriptstyring for ChatGPT",
    "installedTitle": "Aktiver skriptstyring for ChatGPT på nytt",
    "body": "Installering av Incodex endrer ChatGPT, så Tilgjengelighetstillatelsen må gis på nytt.",
    "permissionTitle": "Tilgjengelighet",
    "permissionDescription": "Les og samhandle med appgrensesnitt",
    "repair": "Tillat",
    "later": "Hopp over",
    "back": "Tilbake",
    "addedTitle": "Tillat ChatGPT i Systeminnstillinger",
    "addedBody": "Dra ChatGPT-symbolet ovenfor til Tilgjengelighetslisten og slå det på. Fullfør eventuell macOS-autentisering. Tilgang kontrolleres automatisk; dette vinduet lukkes når tilgangen er klar.",
    "dragInstruction": "Dra ChatGPT til listen ovenfor for å tillate Tilgjengelighet",
    "completeInSettings": "FULLFØR I SYSTEMINNSTILLINGER",
    "checking": "Venter på tilgang · kontrollerer automatisk",
    "repairing": "Forbereder Systeminnstillinger…",
    "openSettings": "Åpne innstillinger",
    "errorTitle": "Oppsett av ChatGPT-tillatelse er ikke fullført",
    "errorBody": "Tillatelsesoppsettet kunne ikke fullføres. Legg til /Applications/ChatGPT.app i Systeminnstillinger → Personvern og sikkerhet → Tilgjengelighet, og kjør deretter incodex install for å kontrollere på nytt."
  },
  "nl-NL": {
    "title": "Scriptbediening voor ChatGPT inschakelen",
    "installedTitle": "Scriptbediening voor ChatGPT opnieuw inschakelen",
    "body": "Door Incodex te installeren wordt ChatGPT gewijzigd. Daarom moet je opnieuw toestemming geven voor Toegankelijkheid.",
    "permissionTitle": "Toegankelijkheid",
    "permissionDescription": "Appinterfaces lezen en ermee werken",
    "repair": "Toestaan",
    "later": "Overslaan",
    "back": "Terug",
    "addedTitle": "ChatGPT toestaan in Systeeminstellingen",
    "addedBody": "Sleep het ChatGPT-symbool hierboven naar de lijst Toegankelijkheid en schakel het in. Voltooi eventuele macOS-authenticatie. Toegang wordt automatisch gecontroleerd; dit venster sluit wanneer de toegang gereed is.",
    "dragInstruction": "Sleep ChatGPT naar de bovenstaande lijst om Toegankelijkheid toe te staan",
    "completeInSettings": "VOLTOOI IN SYSTEEMINSTELLINGEN",
    "checking": "Wachten op toegang · automatisch controleren",
    "repairing": "Systeeminstellingen voorbereiden…",
    "openSettings": "Instellingen openen",
    "errorTitle": "Instellen van ChatGPT-toestemming is niet voltooid",
    "errorBody": "Het instellen van de toestemming kon niet worden voltooid. Voeg /Applications/ChatGPT.app toe in Systeeminstellingen → Privacy en beveiliging → Toegankelijkheid en voer daarna incodex install uit om opnieuw te controleren."
  },
  "pa": {
    "title": "ChatGPT ਸਕ੍ਰਿਪਟ ਕੰਟਰੋਲ ਚਾਲੂ ਕਰੋ",
    "installedTitle": "ChatGPT ਸਕ੍ਰਿਪਟ ਕੰਟਰੋਲ ਦੁਬਾਰਾ ਚਾਲੂ ਕਰੋ",
    "body": "Incodex ਇੰਸਟਾਲ ਕਰਨ ਨਾਲ ChatGPT ਵਿੱਚ ਤਬਦੀਲੀ ਹੁੰਦੀ ਹੈ, ਇਸ ਲਈ ਇਸਦੀ ਪਹੁੰਚਯੋਗਤਾ ਦੀ ਇਜਾਜ਼ਤ ਦੁਬਾਰਾ ਦੇਣੀ ਪਵੇਗੀ।",
    "permissionTitle": "ਪਹੁੰਚਯੋਗਤਾ",
    "permissionDescription": "ਐਪ ਦੇ ਇੰਟਰਫੇਸ ਪੜ੍ਹੋ ਅਤੇ ਉਨ੍ਹਾਂ ਨਾਲ ਇੰਟਰੈਕਟ ਕਰੋ",
    "repair": "ਮਨਜ਼ੂਰ ਕਰੋ",
    "later": "ਛੱਡੋ",
    "back": "ਵਾਪਸ",
    "addedTitle": "ਸਿਸਟਮ ਸੈਟਿੰਗਾਂ ਵਿੱਚ ChatGPT ਨੂੰ ਮਨਜ਼ੂਰੀ ਦਿਓ",
    "addedBody": "ਉੱਪਰ ਦਿੱਤੇ ChatGPT ਆਈਕਨ ਨੂੰ ਪਹੁੰਚਯੋਗਤਾ ਸੂਚੀ ਵਿੱਚ ਖਿੱਚੋ ਅਤੇ ਇਸਨੂੰ ਚਾਲੂ ਕਰੋ। macOS ਦੀ ਕੋਈ ਵੀ ਪ੍ਰਮਾਣਿਕਤਾ ਪੂਰੀ ਕਰੋ। ਪਹੁੰਚ ਆਪਣੇ ਆਪ ਜਾਂਚੀ ਜਾਂਦੀ ਹੈ; ਪਹੁੰਚ ਤਿਆਰ ਹੋਣ 'ਤੇ ਇਹ ਵਿੰਡੋ ਬੰਦ ਹੋ ਜਾਵੇਗੀ।",
    "dragInstruction": "ਪਹੁੰਚਯੋਗਤਾ ਦੀ ਮਨਜ਼ੂਰੀ ਦੇਣ ਲਈ ChatGPT ਨੂੰ ਉੱਪਰ ਦਿੱਤੀ ਸੂਚੀ ਵਿੱਚ ਖਿੱਚੋ",
    "completeInSettings": "ਸਿਸਟਮ ਸੈਟਿੰਗਾਂ ਵਿੱਚ ਪੂਰਾ ਕਰੋ",
    "checking": "ਪਹੁੰਚ ਦੀ ਉਡੀਕ · ਆਪਣੇ ਆਪ ਜਾਂਚ ਜਾਰੀ",
    "repairing": "ਸਿਸਟਮ ਸੈਟਿੰਗਾਂ ਤਿਆਰ ਕੀਤੀਆਂ ਜਾ ਰਹੀਆਂ ਹਨ…",
    "openSettings": "ਸੈਟਿੰਗਾਂ ਖੋਲ੍ਹੋ",
    "errorTitle": "ChatGPT ਦੀ ਇਜਾਜ਼ਤ ਸੈਟਅੱਪ ਪੂਰੀ ਨਹੀਂ ਹੋਈ",
    "errorBody": "ਇਜਾਜ਼ਤ ਸੈਟਅੱਪ ਪੂਰਾ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਸਿਸਟਮ ਸੈਟਿੰਗਾਂ → ਪਰਦੇਦਾਰੀ ਅਤੇ ਸੁਰੱਖਿਆ → ਪਹੁੰਚਯੋਗਤਾ ਵਿੱਚ /Applications/ChatGPT.app ਸ਼ਾਮਲ ਕਰੋ, ਫਿਰ ਦੁਬਾਰਾ ਜਾਂਚ ਕਰਨ ਲਈ incodex install ਚਲਾਓ।"
  },
  "pl-PL": {
    "title": "Włącz sterowanie skryptami w ChatGPT",
    "installedTitle": "Ponownie włącz sterowanie skryptami w ChatGPT",
    "body": "Instalacja Incodex modyfikuje ChatGPT, dlatego uprawnienie Dostępność trzeba nadać ponownie.",
    "permissionTitle": "Dostępność",
    "permissionDescription": "Czytaj interfejsy aplikacji i wchodź z nimi w interakcję",
    "repair": "Zezwól",
    "later": "Pomiń",
    "back": "Wstecz",
    "addedTitle": "Zezwól na ChatGPT w Ustawieniach systemowych",
    "addedBody": "Przeciągnij znajdującą się wyżej ikonę ChatGPT na listę Dostępność i włącz ją. Ukończ wszelkie uwierzytelnianie systemu macOS. Dostęp jest sprawdzany automatycznie; to okno zamknie się, gdy dostęp będzie gotowy.",
    "dragInstruction": "Przeciągnij ChatGPT na powyższą listę, aby zezwolić na Dostępność",
    "completeInSettings": "DOKOŃCZ W USTAWIENIACH SYSTEMOWYCH",
    "checking": "Oczekiwanie na dostęp · automatyczne sprawdzanie",
    "repairing": "Przygotowywanie Ustawień systemowych…",
    "openSettings": "Otwórz ustawienia",
    "errorTitle": "Konfiguracja uprawnienia ChatGPT nie została ukończona",
    "errorBody": "Nie udało się ukończyć konfiguracji uprawnienia. Dodaj /Applications/ChatGPT.app w Ustawieniach systemowych → Prywatność i ochrona → Dostępność, a następnie uruchom incodex install, aby sprawdzić ponownie."
  },
  "pt-BR": {
    "title": "Ativar controle de scripts do ChatGPT",
    "installedTitle": "Ativar novamente o controle de scripts do ChatGPT",
    "body": "A instalação do Incodex modifica o ChatGPT, então a permissão de Acessibilidade precisa ser concedida novamente.",
    "permissionTitle": "Acessibilidade",
    "permissionDescription": "Ler e interagir com interfaces de apps",
    "repair": "Permitir",
    "later": "Pular",
    "back": "Voltar",
    "addedTitle": "Permitir o ChatGPT nos Ajustes do Sistema",
    "addedBody": "Arraste o ícone do ChatGPT acima para a lista de Acessibilidade e ative-o. Conclua qualquer autenticação do macOS. O acesso é verificado automaticamente; esta janela será fechada quando o acesso estiver pronto.",
    "dragInstruction": "Arraste o ChatGPT para a lista acima para permitir a Acessibilidade",
    "completeInSettings": "CONCLUIR NOS AJUSTES DO SISTEMA",
    "checking": "Aguardando acesso · verificando automaticamente",
    "repairing": "Preparando os Ajustes do Sistema…",
    "openSettings": "Abrir Ajustes",
    "errorTitle": "A configuração da permissão do ChatGPT está incompleta",
    "errorBody": "Não foi possível concluir a configuração da permissão. Adicione /Applications/ChatGPT.app em Ajustes do Sistema → Privacidade e Segurança → Acessibilidade e execute incodex install para verificar novamente."
  },
  "pt-PT": {
    "title": "Ativar o controlo de scripts do ChatGPT",
    "installedTitle": "Ativar novamente o controlo de scripts do ChatGPT",
    "body": "A instalação do Incodex modifica o ChatGPT, por isso a permissão de Acessibilidade tem de ser concedida novamente.",
    "permissionTitle": "Acessibilidade",
    "permissionDescription": "Ler e interagir com interfaces de aplicações",
    "repair": "Permitir",
    "later": "Ignorar",
    "back": "Voltar",
    "addedTitle": "Permitir o ChatGPT nas Definições do Sistema",
    "addedBody": "Arraste o ícone do ChatGPT acima para a lista de Acessibilidade e ative-o. Conclua qualquer autenticação do macOS. O acesso é verificado automaticamente; esta janela fecha quando o acesso estiver pronto.",
    "dragInstruction": "Arraste o ChatGPT para a lista acima para permitir a Acessibilidade",
    "completeInSettings": "CONCLUIR NAS DEFINIÇÕES DO SISTEMA",
    "checking": "A aguardar acesso · verificação automática",
    "repairing": "A preparar as Definições do Sistema…",
    "openSettings": "Abrir definições",
    "errorTitle": "A configuração da permissão do ChatGPT está incompleta",
    "errorBody": "Não foi possível concluir a configuração da permissão. Adicione /Applications/ChatGPT.app em Definições do Sistema → Privacidade e Segurança → Acessibilidade e execute incodex install para verificar novamente."
  },
  "ro-RO": {
    "title": "Activați controlul scripturilor pentru ChatGPT",
    "installedTitle": "Reactivați controlul scripturilor pentru ChatGPT",
    "body": "Instalarea Incodex modifică ChatGPT, astfel că permisiunea Accesibilitate trebuie acordată din nou.",
    "permissionTitle": "Accesibilitate",
    "permissionDescription": "Citiți interfețele aplicațiilor și interacționați cu acestea",
    "repair": "Permiteți",
    "later": "Omiteți",
    "back": "Înapoi",
    "addedTitle": "Permiteți ChatGPT în Configurări sistem",
    "addedBody": "Trageți pictograma ChatGPT de mai sus în lista Accesibilitate și activați-o. Finalizați orice autentificare macOS. Accesul este verificat automat; această fereastră se va închide când accesul este pregătit.",
    "dragInstruction": "Trageți ChatGPT în lista de mai sus pentru a permite Accesibilitatea",
    "completeInSettings": "FINALIZAȚI ÎN CONFIGURĂRI SISTEM",
    "checking": "Se așteaptă accesul · verificare automată",
    "repairing": "Se pregătesc configurările sistemului…",
    "openSettings": "Deschideți configurările",
    "errorTitle": "Configurarea permisiunii ChatGPT nu este finalizată",
    "errorBody": "Configurarea permisiunii nu a putut fi finalizată. Adăugați /Applications/ChatGPT.app în Configurări sistem → Intimitate și securitate → Accesibilitate, apoi rulați incodex install pentru a verifica din nou."
  },
  "ru-RU": {
    "title": "Включить управление скриптами ChatGPT",
    "installedTitle": "Повторно включить управление скриптами ChatGPT",
    "body": "Установка Incodex изменяет ChatGPT, поэтому разрешение «Универсальный доступ» нужно предоставить повторно.",
    "permissionTitle": "Универсальный доступ",
    "permissionDescription": "Читайте интерфейсы приложений и взаимодействуйте с ними",
    "repair": "Разрешить",
    "later": "Пропустить",
    "back": "Назад",
    "addedTitle": "Разрешить ChatGPT в системных настройках",
    "addedBody": "Перетащите расположенный выше значок ChatGPT в список «Универсальный доступ» и включите его. Пройдите необходимую аутентификацию macOS. Доступ проверяется автоматически; это окно закроется, когда доступ будет готов.",
    "dragInstruction": "Перетащите ChatGPT в список выше, чтобы разрешить «Универсальный доступ»",
    "completeInSettings": "ЗАВЕРШИТЕ В СИСТЕМНЫХ НАСТРОЙКАХ",
    "checking": "Ожидание доступа · автоматическая проверка",
    "repairing": "Подготовка системных настроек…",
    "openSettings": "Открыть настройки",
    "errorTitle": "Настройка разрешения для ChatGPT не завершена",
    "errorBody": "Не удалось завершить настройку разрешения. Добавьте /Applications/ChatGPT.app в Системные настройки → Конфиденциальность и безопасность → Универсальный доступ, затем запустите incodex install для повторной проверки."
  },
  "sk-SK": {
    "title": "Povoliť ovládanie skriptov pre ChatGPT",
    "installedTitle": "Znova povoliť ovládanie skriptov pre ChatGPT",
    "body": "Inštalácia Incodex upraví ChatGPT, preto je potrebné znova udeliť povolenie Prístupnosť.",
    "permissionTitle": "Prístupnosť",
    "permissionDescription": "Čítať rozhrania aplikácií a pracovať s nimi",
    "repair": "Povoliť",
    "later": "Preskočiť",
    "back": "Späť",
    "addedTitle": "Povoliť ChatGPT v systémových nastaveniach",
    "addedBody": "Presuňte ikonu ChatGPT vyššie do zoznamu Prístupnosť a povoľte ju. Dokončite prípadnú autentifikáciu macOS. Prístup sa kontroluje automaticky; toto okno sa zavrie, keď bude prístup pripravený.",
    "dragInstruction": "Presuňte ChatGPT do zoznamu vyššie a povoľte Prístupnosť",
    "completeInSettings": "DOKONČITE V SYSTÉMOVÝCH NASTAVENIACH",
    "checking": "Čaká sa na prístup · kontroluje sa automaticky",
    "repairing": "Pripravujú sa systémové nastavenia…",
    "openSettings": "Otvoriť nastavenia",
    "errorTitle": "Nastavenie povolenia pre ChatGPT nie je dokončené",
    "errorBody": "Nastavenie povolenia sa nepodarilo dokončiť. V Systémových nastaveniach → Súkromie a bezpečnosť → Prístupnosť pridajte /Applications/ChatGPT.app a potom spustite incodex install na opätovnú kontrolu."
  },
  "sl-SI": {
    "title": "Omogočite nadzor skriptov ChatGPT",
    "installedTitle": "Znova omogočite nadzor skriptov ChatGPT",
    "body": "Namestitev Incodex spremeni ChatGPT, zato je treba dovoljenje za Dostopnost dodeliti znova.",
    "permissionTitle": "Dostopnost",
    "permissionDescription": "Branje vmesnikov aplikacij in interakcija z njimi",
    "repair": "Dovoli",
    "later": "Preskoči",
    "back": "Nazaj",
    "addedTitle": "Dovolite ChatGPT v sistemskih nastavitvah",
    "addedBody": "Povlecite zgornjo ikono ChatGPT na seznam Dostopnost in jo omogočite. Dokončajte morebitno preverjanje pristnosti macOS. Dostop se preverja samodejno; to okno se bo zaprlo, ko bo dostop pripravljen.",
    "dragInstruction": "Povlecite ChatGPT na zgornji seznam, da dovolite Dostopnost",
    "completeInSettings": "DOKONČAJTE V SISTEMSKIH NASTAVITVAH",
    "checking": "Čakanje na dostop · samodejno preverjanje",
    "repairing": "Pripravljanje sistemskih nastavitev…",
    "openSettings": "Odpri nastavitve",
    "errorTitle": "Nastavitev dovoljenja za ChatGPT ni dokončana",
    "errorBody": "Nastavitve dovoljenja ni bilo mogoče dokončati. V sistemskih nastavitvah → Zasebnost in varnost → Dostopnost dodajte /Applications/ChatGPT.app, nato za vnovično preverjanje zaženite incodex install."
  },
  "so-SO": {
    "title": "Daar xakamaynta qoraalka ChatGPT",
    "installedTitle": "Daar xakamaynta qoraalka ChatGPT mar kale",
    "body": "Rakibidda Incodex waxay wax ka beddeshaa ChatGPT, sidaas darteed oggolaanshaha Helitaanka waa in mar kale la bixiyaa.",
    "permissionTitle": "Helitaanka",
    "permissionDescription": "Akhri oo la falgal is-dhexgallada abka",
    "repair": "Oggolow",
    "later": "Ka bood",
    "back": "Dib u noqo",
    "addedTitle": "U oggolow ChatGPT Dejinta Nidaamka",
    "addedBody": "U jiid astaanta ChatGPT ee kore liiska Helitaanka oo daar. Dhammaystir xaqiijin kasta oo macOS ah. Helitaanka si toos ah ayaa loo hubiyaa; daaqaddan way xirmi doontaa marka helitaanku diyaar noqdo.",
    "dragInstruction": "ChatGPT u jiid liiska kore si aad u oggolaato Helitaanka",
    "completeInSettings": "KU DHAMMEE DEJINTA NIDAAMKA",
    "checking": "Helitaan ayaa la sugayaa · si toos ah ayaa loo hubinayaa",
    "repairing": "Dejinta Nidaamka ayaa la diyaarinayaa…",
    "openSettings": "Fur Dejinta",
    "errorTitle": "Dejinta oggolaanshaha ChatGPT ma dhammaystirna",
    "errorBody": "Dejinta oggolaanshaha lama dhammaystiri karin. Ku dar /Applications/ChatGPT.app Dejinta Nidaamka → Asturnaanta iyo amniga → Helitaanka, ka dibna socodsii incodex install si mar kale loo hubiyo."
  },
  "sq-AL": {
    "title": "Aktivizo kontrollin e skripteve të ChatGPT",
    "installedTitle": "Riaktivizo kontrollin e skripteve të ChatGPT",
    "body": "Instalimi i Incodex modifikon ChatGPT, ndaj leja e Aksesueshmërisë duhet të jepet përsëri.",
    "permissionTitle": "Aksesueshmëria",
    "permissionDescription": "Lexo ndërfaqet e aplikacioneve dhe ndërvepro me to",
    "repair": "Lejo",
    "later": "Anashkalo",
    "back": "Prapa",
    "addedTitle": "Lejo ChatGPT te Cilësimet e sistemit",
    "addedBody": "Tërhiq ikonën e ChatGPT më sipër në listën e Aksesueshmërisë dhe aktivizoje. Përfundo çdo autentikim të macOS. Qasja kontrollohet automatikisht; kjo dritare mbyllet kur qasja të jetë gati.",
    "dragInstruction": "Tërhiq ChatGPT në listën më sipër për të lejuar Aksesueshmërinë",
    "completeInSettings": "PËRFUNDO TE CILËSIMET E SISTEMIT",
    "checking": "Po pritet qasja · po kontrollohet automatikisht",
    "repairing": "Po përgatiten cilësimet e sistemit…",
    "openSettings": "Hap cilësimet",
    "errorTitle": "Konfigurimi i lejes së ChatGPT nuk ka përfunduar",
    "errorBody": "Konfigurimi i lejes nuk mund të përfundonte. Shtoni /Applications/ChatGPT.app te Cilësimet e sistemit → Privatësia dhe siguria → Aksesueshmëria, më pas ekzekutoni incodex install për ta kontrolluar përsëri."
  },
  "sr-RS": {
    "title": "Омогућите контролу ChatGPT скриптама",
    "installedTitle": "Поново омогућите контролу ChatGPT скриптама",
    "body": "Инсталација апликације Incodex мења ChatGPT, па дозволу за Приступачност треба поново доделити.",
    "permissionTitle": "Приступачност",
    "permissionDescription": "Читајте интерфејсе апликација и остварујте интеракцију са њима",
    "repair": "Дозволи",
    "later": "Прескочи",
    "back": "Назад",
    "addedTitle": "Дозволите ChatGPT у системским подешавањима",
    "addedBody": "Превуците икону ChatGPT изнад на листу Приступачност и омогућите је. Завршите сваку потврду идентитета за macOS. Приступ се проверава аутоматски; овај прозор ће се затворити када приступ буде спреман.",
    "dragInstruction": "Превуците ChatGPT на листу изнад да бисте дозволили Приступачност",
    "completeInSettings": "ЗАВРШИТЕ У СИСТЕМСКИМ ПОДЕШАВАЊИМА",
    "checking": "Чека се приступ · аутоматска провера",
    "repairing": "Припремају се системска подешавања…",
    "openSettings": "Отвори подешавања",
    "errorTitle": "Подешавање дозволе за ChatGPT није завршено",
    "errorBody": "Подешавање дозволе није могло да се заврши. Додајте /Applications/ChatGPT.app у Системска подешавања → Приватност и безбедност → Приступачност, а затим покрените incodex install да бисте поново проверили."
  },
  "sv-SE": {
    "title": "Aktivera skriptstyrning för ChatGPT",
    "installedTitle": "Aktivera skriptstyrning för ChatGPT igen",
    "body": "När Incodex installeras ändras ChatGPT, så behörigheten Hjälpmedel måste beviljas igen.",
    "permissionTitle": "Hjälpmedel",
    "permissionDescription": "Läs och interagera med appgränssnitt",
    "repair": "Tillåt",
    "later": "Hoppa över",
    "back": "Tillbaka",
    "addedTitle": "Tillåt ChatGPT i Systeminställningar",
    "addedBody": "Dra ChatGPT-symbolen ovan till listan Hjälpmedel och aktivera den. Slutför eventuell macOS-autentisering. Åtkomsten kontrolleras automatiskt; det här fönstret stängs när åtkomsten är klar.",
    "dragInstruction": "Dra ChatGPT till listan ovan för att tillåta Hjälpmedel",
    "completeInSettings": "SLUTFÖR I SYSTEMINSTÄLLNINGAR",
    "checking": "Väntar på åtkomst · kontrollerar automatiskt",
    "repairing": "Förbereder Systeminställningar…",
    "openSettings": "Öppna inställningar",
    "errorTitle": "Inställningen av ChatGPT-behörigheten är inte klar",
    "errorBody": "Det gick inte att slutföra behörighetsinställningen. Lägg till /Applications/ChatGPT.app i Systeminställningar → Integritet och säkerhet → Hjälpmedel och kör sedan incodex install för att kontrollera igen."
  },
  "sw-TZ": {
    "title": "Washa udhibiti wa hati za ChatGPT",
    "installedTitle": "Washa tena udhibiti wa hati za ChatGPT",
    "body": "Kusakinisha Incodex hubadilisha ChatGPT, kwa hivyo ruhusa ya Ufikivu lazima itolewe tena.",
    "permissionTitle": "Ufikivu",
    "permissionDescription": "Soma na uwasiliane na violesura vya programu",
    "repair": "Ruhusu",
    "later": "Ruka",
    "back": "Rudi",
    "addedTitle": "Ruhusu ChatGPT katika Mipangilio ya Mfumo",
    "addedBody": "Buruta ikoni ya ChatGPT iliyo hapo juu hadi kwenye orodha ya Ufikivu na uiwashe. Kamilisha uthibitishaji wowote wa macOS. Ufikiaji hukaguliwa kiotomatiki; dirisha hili litafungwa ufikiaji ukiwa tayari.",
    "dragInstruction": "Buruta ChatGPT kwenye orodha iliyo hapo juu ili kuruhusu Ufikivu",
    "completeInSettings": "KAMILISHA KATIKA MIPANGILIO YA MFUMO",
    "checking": "Inasubiri ufikiaji · inakagua kiotomatiki",
    "repairing": "Inatayarisha Mipangilio ya Mfumo…",
    "openSettings": "Fungua Mipangilio",
    "errorTitle": "Usanidi wa ruhusa ya ChatGPT haujakamilika",
    "errorBody": "Usanidi wa ruhusa haukuweza kukamilika. Ongeza /Applications/ChatGPT.app katika Mipangilio ya Mfumo → Faragha na Usalama → Ufikivu, kisha endesha incodex install ili uangalie tena."
  },
  "ta-IN": {
    "title": "ChatGPT ஸ்கிரிப்ட் கட்டுப்பாட்டை இயக்கவும்",
    "installedTitle": "ChatGPT ஸ்கிரிப்ட் கட்டுப்பாட்டை மீண்டும் இயக்கவும்",
    "body": "Incodex-ஐ நிறுவுவது ChatGPT-ஐ மாற்றுவதால், அதன் அணுகல்தன்மை அனுமதியை மீண்டும் வழங்க வேண்டும்.",
    "permissionTitle": "அணுகல்தன்மை",
    "permissionDescription": "ஆப்ஸ் இடைமுகங்களைப் படித்து அவற்றுடன் தொடர்புகொள்ளவும்",
    "repair": "அனுமதி",
    "later": "தவிர்",
    "back": "பின்செல்",
    "addedTitle": "கணினி அமைப்புகளில் ChatGPT-ஐ அனுமதிக்கவும்",
    "addedBody": "மேலே உள்ள ChatGPT ஐகானை அணுகல்தன்மை பட்டியலுக்கு இழுத்து, அதை இயக்கவும். macOS கேட்கும் எந்த அங்கீகாரத்தையும் நிறைவு செய்யவும். அணுகல் தானாகச் சரிபார்க்கப்படும்; அணுகல் தயாரானதும் இந்தச் சாளரம் மூடப்படும்.",
    "dragInstruction": "அணுகல்தன்மையை அனுமதிக்க ChatGPT-ஐ மேலே உள்ள பட்டியலுக்கு இழுக்கவும்",
    "completeInSettings": "கணினி அமைப்புகளில் நிறைவு செய்யவும்",
    "checking": "அணுகலுக்காகக் காத்திருக்கிறது · தானாகச் சரிபார்க்கிறது",
    "repairing": "கணினி அமைப்புகளைத் தயாரிக்கிறது…",
    "openSettings": "அமைப்புகளைத் திற",
    "errorTitle": "ChatGPT அனுமதி அமைப்பு முழுமையடையவில்லை",
    "errorBody": "அனுமதி அமைப்பை முடிக்க முடியவில்லை. கணினி அமைப்புகள் → தனியுரிமை மற்றும் பாதுகாப்பு → அணுகல்தன்மை என்பதில் /Applications/ChatGPT.app-ஐச் சேர்த்து, மீண்டும் சரிபார்க்க incodex install-ஐ இயக்கவும்."
  },
  "te-IN": {
    "title": "ChatGPT స్క్రిప్ట్ నియంత్రణను ప్రారంభించండి",
    "installedTitle": "ChatGPT స్క్రిప్ట్ నియంత్రణను మళ్లీ ప్రారంభించండి",
    "body": "Incodexను ఇన్‌స్టాల్ చేయడం వల్ల ChatGPTలో మార్పులు జరుగుతాయి, కాబట్టి దాని యాక్సెసిబిలిటీ అనుమతిని మళ్లీ ఇవ్వాలి.",
    "permissionTitle": "యాక్సెసిబిలిటీ",
    "permissionDescription": "యాప్ ఇంటర్‌ఫేస్‌లను చదివి వాటితో పరస్పర చర్య చేయండి",
    "repair": "అనుమతించు",
    "later": "దాటవేయి",
    "back": "వెనుకకు",
    "addedTitle": "సిస్టమ్ సెట్టింగ్‌లలో ChatGPTను అనుమతించండి",
    "addedBody": "పై ఉన్న ChatGPT చిహ్నాన్ని యాక్సెసిబిలిటీ జాబితాలోకి లాగి, దాన్ని ప్రారంభించండి. macOS కోరే ఏదైనా ప్రమాణీకరణను పూర్తి చేయండి. యాక్సెస్ స్వయంచాలకంగా తనిఖీ చేయబడుతుంది; యాక్సెస్ సిద్ధమైనప్పుడు ఈ విండో మూసుకుపోతుంది.",
    "dragInstruction": "యాక్సెసిబిలిటీని అనుమతించడానికి ChatGPTను పై జాబితాలోకి లాగండి",
    "completeInSettings": "సిస్టమ్ సెట్టింగ్‌లలో పూర్తి చేయండి",
    "checking": "యాక్సెస్ కోసం వేచి ఉంది · స్వయంచాలకంగా తనిఖీ చేస్తోంది",
    "repairing": "సిస్టమ్ సెట్టింగ్‌లను సిద్ధం చేస్తోంది…",
    "openSettings": "సెట్టింగ్‌లను తెరవండి",
    "errorTitle": "ChatGPT అనుమతి సెటప్ పూర్తికాలేదు",
    "errorBody": "అనుమతి సెటప్‌ను పూర్తి చేయలేకపోయాం. సిస్టమ్ సెట్టింగ్‌లు → గోప్యత & భద్రత → యాక్సెసిబిలిటీలో /Applications/ChatGPT.appను జోడించి, మళ్లీ తనిఖీ చేయడానికి incodex installను అమలు చేయండి."
  },
  "th-TH": {
    "title": "เปิดใช้การควบคุมสคริปต์ของ ChatGPT",
    "installedTitle": "เปิดใช้การควบคุมสคริปต์ของ ChatGPT อีกครั้ง",
    "body": "การติดตั้ง Incodex จะปรับเปลี่ยน ChatGPT จึงต้องอนุญาตสิทธิ์การช่วยการเข้าถึงอีกครั้ง",
    "permissionTitle": "การช่วยการเข้าถึง",
    "permissionDescription": "อ่านและโต้ตอบกับอินเทอร์เฟซของแอป",
    "repair": "อนุญาต",
    "later": "ข้าม",
    "back": "ย้อนกลับ",
    "addedTitle": "อนุญาต ChatGPT ในการตั้งค่าระบบ",
    "addedBody": "ลากไอคอน ChatGPT ด้านบนไปยังรายการการช่วยการเข้าถึง แล้วเปิดใช้ ทำการตรวจสอบสิทธิ์ของ macOS ให้เสร็จสิ้น การเข้าถึงจะได้รับการตรวจสอบโดยอัตโนมัติ หน้าต่างนี้จะปิดเมื่อการเข้าถึงพร้อมใช้งาน",
    "dragInstruction": "ลาก ChatGPT ไปยังรายการด้านบนเพื่ออนุญาตการช่วยการเข้าถึง",
    "completeInSettings": "ดำเนินการให้เสร็จในแอปการตั้งค่าระบบ",
    "checking": "กำลังรอการเข้าถึง · กำลังตรวจสอบโดยอัตโนมัติ",
    "repairing": "กำลังเตรียมการตั้งค่าระบบ…",
    "openSettings": "เปิดการตั้งค่า",
    "errorTitle": "การตั้งค่าสิทธิ์ของ ChatGPT ยังไม่เสร็จสมบูรณ์",
    "errorBody": "ไม่สามารถตั้งค่าสิทธิ์ให้เสร็จได้ เพิ่ม /Applications/ChatGPT.app ในการตั้งค่าระบบ → ความเป็นส่วนตัวและความปลอดภัย → การช่วยการเข้าถึง จากนั้นเรียกใช้ incodex install เพื่อตรวจสอบอีกครั้ง"
  },
  "tl": {
    "title": "I-enable ang script control ng ChatGPT",
    "installedTitle": "Paganahin muli ang script control ng ChatGPT",
    "body": "Binabago ng pag-install ng Incodex ang ChatGPT, kaya kailangang ibigay muli ang pahintulot sa Accessibility nito.",
    "permissionTitle": "Accessibility",
    "permissionDescription": "Basahin at makipag-ugnayan sa mga interface ng app",
    "repair": "Payagan",
    "later": "Laktawan",
    "back": "Bumalik",
    "addedTitle": "Payagan ang ChatGPT sa Mga Setting ng System",
    "addedBody": "I-drag ang icon ng ChatGPT sa itaas papunta sa listahan ng Accessibility at i-enable ito. Kumpletuhin ang anumang authentication ng macOS. Awtomatikong sinusuri ang access; magsasara ang window na ito kapag handa na ang access.",
    "dragInstruction": "I-drag ang ChatGPT sa listahan sa itaas para payagan ang Accessibility",
    "completeInSettings": "KUMPLETUHIN SA MGA SETTING NG SYSTEM",
    "checking": "Naghihintay ng access · awtomatikong sinusuri",
    "repairing": "Inihahanda ang Mga Setting ng System…",
    "openSettings": "Buksan ang Mga Setting",
    "errorTitle": "Hindi kumpleto ang pag-set up ng pahintulot ng ChatGPT",
    "errorBody": "Hindi nakumpleto ang pag-set up ng pahintulot. Idagdag ang /Applications/ChatGPT.app sa Mga Setting ng System → Privacy at Seguridad → Accessibility, pagkatapos ay patakbuhin ang incodex install para muling magsuri."
  },
  "tr-TR": {
    "title": "ChatGPT komut dosyası denetimini etkinleştir",
    "installedTitle": "ChatGPT komut dosyası denetimini yeniden etkinleştir",
    "body": "Incodex'i yüklemek ChatGPT'yi değiştirir, bu nedenle Erişilebilirlik izninin yeniden verilmesi gerekir.",
    "permissionTitle": "Erişilebilirlik",
    "permissionDescription": "Uygulama arayüzlerini okuyun ve bunlarla etkileşime geçin",
    "repair": "İzin Ver",
    "later": "Atla",
    "back": "Geri",
    "addedTitle": "Sistem Ayarları'nda ChatGPT'ye izin ver",
    "addedBody": "Yukarıdaki ChatGPT simgesini Erişilebilirlik listesine sürükleyip etkinleştirin. Gerekli macOS kimlik doğrulamasını tamamlayın. Erişim otomatik olarak denetlenir; erişim hazır olduğunda bu pencere kapanır.",
    "dragInstruction": "Erişilebilirliğe izin vermek için ChatGPT'yi yukarıdaki listeye sürükleyin",
    "completeInSettings": "SİSTEM AYARLARINDA TAMAMLAYIN",
    "checking": "Erişim bekleniyor · otomatik denetleniyor",
    "repairing": "Sistem Ayarları hazırlanıyor…",
    "openSettings": "Ayarları Aç",
    "errorTitle": "ChatGPT izin ayarı tamamlanmadı",
    "errorBody": "İzin ayarı tamamlanamadı. Sistem Ayarları → Gizlilik ve Güvenlik → Erişilebilirlik bölümüne /Applications/ChatGPT.app ekleyin, ardından yeniden denetlemek için incodex install komutunu çalıştırın."
  },
  "uk-UA": {
    "title": "Увімкнути керування скриптами ChatGPT",
    "installedTitle": "Повторно ввімкнути керування скриптами ChatGPT",
    "body": "Інсталяція Incodex змінює ChatGPT, тому дозвіл «Доступність» потрібно надати знову.",
    "permissionTitle": "Доступність",
    "permissionDescription": "Читайте інтерфейси програм і взаємодійте з ними",
    "repair": "Дозволити",
    "later": "Пропустити",
    "back": "Назад",
    "addedTitle": "Дозволити ChatGPT у системних параметрах",
    "addedBody": "Перетягніть розташовану вище піктограму ChatGPT до списку «Доступність» та ввімкніть її. Завершіть автентифікацію macOS, якщо буде потрібно. Доступ перевіряється автоматично; це вікно закриється, коли доступ буде готовий.",
    "dragInstruction": "Перетягніть ChatGPT до списку «Доступність» вище, щоб надати дозвіл",
    "completeInSettings": "ЗАВЕРШІТЬ У СИСТЕМНИХ ПАРАМЕТРАХ",
    "checking": "Очікування доступу · автоматична перевірка",
    "repairing": "Підготовка системних параметрів…",
    "openSettings": "Відкрити параметри",
    "errorTitle": "Налаштування дозволу для ChatGPT не завершено",
    "errorBody": "Не вдалося завершити налаштування дозволу. Додайте /Applications/ChatGPT.app у Системні параметри → Конфіденційність і безпека → Доступність, потім запустіть incodex install для повторної перевірки."
  },
  "ur": {
    "title": "ChatGPT اسکرپٹ کنٹرول فعال کریں",
    "installedTitle": "ChatGPT اسکرپٹ کنٹرول دوبارہ فعال کریں",
    "body": "Incodex انسٹال کرنے سے ChatGPT میں تبدیلیاں ہوتی ہیں، اس لیے اس کی قابلِ رسائی کی اجازت دوبارہ دینی ہوگی۔",
    "permissionTitle": "قابلِ رسائی",
    "permissionDescription": "ایپ کے انٹرفیس پڑھیں اور ان کے ساتھ تعامل کریں",
    "repair": "اجازت دیں",
    "later": "چھوڑیں",
    "back": "واپس",
    "addedTitle": "سسٹم سیٹنگز میں ChatGPT کو اجازت دیں",
    "addedBody": "اوپر موجود ChatGPT آئیکن کو قابلِ رسائی فہرست میں گھسیٹیں اور اسے فعال کریں۔ macOS کی کسی بھی توثیق کو مکمل کریں۔ رسائی خودکار طور پر چیک کی جاتی ہے؛ رسائی تیار ہونے پر یہ ونڈو بند ہو جائے گی۔",
    "dragInstruction": "قابلِ رسائی کی اجازت دینے کے لیے ChatGPT کو اوپر موجود فہرست میں گھسیٹیں",
    "completeInSettings": "سسٹم سیٹنگز میں مکمل کریں",
    "checking": "رسائی کا انتظار ہے · خودکار طور پر چیک ہو رہا ہے",
    "repairing": "سسٹم سیٹنگز تیار کی جا رہی ہیں…",
    "openSettings": "سیٹنگز کھولیں",
    "errorTitle": "ChatGPT کی اجازت کا سیٹ اپ نامکمل ہے",
    "errorBody": "اجازت کا سیٹ اپ مکمل نہیں ہو سکا۔ سسٹم سیٹنگز → رازداری اور سیکیورٹی → قابلِ رسائی میں /Applications/ChatGPT.app شامل کریں، پھر دوبارہ چیک کرنے کے لیے incodex install چلائیں۔"
  },
  "vi-VN": {
    "title": "Bật điều khiển tập lệnh ChatGPT",
    "installedTitle": "Bật lại điều khiển tập lệnh ChatGPT",
    "body": "Việc cài đặt Incodex sửa đổi ChatGPT, vì vậy cần cấp lại quyền Trợ năng.",
    "permissionTitle": "Trợ năng",
    "permissionDescription": "Đọc và tương tác với giao diện ứng dụng",
    "repair": "Cho phép",
    "later": "Bỏ qua",
    "back": "Quay lại",
    "addedTitle": "Cho phép ChatGPT trong Cài đặt hệ thống",
    "addedBody": "Kéo biểu tượng ChatGPT ở trên vào danh sách Trợ năng và bật quyền. Hoàn tất mọi yêu cầu xác thực của macOS. Quyền truy cập được kiểm tra tự động; cửa sổ này sẽ đóng khi quyền truy cập sẵn sàng.",
    "dragInstruction": "Kéo ChatGPT vào danh sách ở trên để cho phép Trợ năng",
    "completeInSettings": "HOÀN TẤT TRONG CÀI ĐẶT HỆ THỐNG",
    "checking": "Đang chờ quyền truy cập · đang tự động kiểm tra",
    "repairing": "Đang chuẩn bị Cài đặt hệ thống…",
    "openSettings": "Mở Cài đặt",
    "errorTitle": "Thiết lập quyền cho ChatGPT chưa hoàn tất",
    "errorBody": "Không thể hoàn tất thiết lập quyền. Hãy thêm /Applications/ChatGPT.app trong Cài đặt hệ thống → Quyền riêng tư & Bảo mật → Trợ năng, sau đó chạy incodex install để kiểm tra lại."
  }
} as const;
