export type CopyKey = "open" | "exit" | "title" | "body" | "dismiss" | "errorTitle" | "errorBody" | "errorRetry" | "errorClose";
export type CopyTable = Record<CopyKey, string>;

// Official Codex UI locales from ../locales/*.json; source copy stays in the resolver.
export const COPY: Record<string, CopyTable> = {
  am: {
    open: "የግል መስኮት ክፈት",
    exit: "የግል መስኮትን ውጣ",
    title: "የግል መስኮት",
    body: "መለያ እና ቅንብሮች እንደተለመደው ናቸው፣ ቀደም ያሉ ውይይቶች አይመጡም። ይህን መስኮት ሲዘጉ ይህ ውይይት አይቀመጥም።",
    dismiss: "የግል መስኮት ማስታወቂያን ዝጋ",
    errorTitle: 'የግል መስኮት መክፈት አልተቻለም',
    errorBody: 'እንደገና ይሞክሩ። ካልሆነ Codex ን ዝጉና እንደገና ይክፈቱ።',
    errorRetry: 'እንደገና ሞክር',
    errorClose: 'ዝጋ',
  },  ar: {
    open: "فتح نافذة التصفح المتخفي",
    exit: "الخروج من نافذة التصفح المتخفي",
    title: "نافذة التصفح المتخفي",
    body: "الحساب والإعدادات كما هي عادةً، دون المحادثات السابقة. أغلق هذه النافذة ولن يُحفظ سجل هذه المحادثة.",
    dismiss: "إغلاق بانر التصفح المتخفي",
    errorTitle: 'تعذّر فتح نافذة التصفح المتخفي',
    errorBody: 'حاول مرة أخرى. إذا استمر الفشل، أغلق Codex ثم افتحه من جديد.',
    errorRetry: 'إعادة المحاولة',
    errorClose: 'إغلاق',
  },
  "bg-BG": {
    open: "Отваряне на прозорец инкогнито",
    exit: "Изход от прозорец инкогнито",
    title: "Прозорец инкогнито",
    body: "Акаунтът и настройките са както обикновено, без предишни разговори. Затворете този прозорец и този чат няма да остави запис.",
    dismiss: "Затваряне на банера за инкогнито",
    errorTitle: 'Прозорецът инкогнито не можа да се отвори',
    errorBody: 'Опитайте отново. Ако пак не стане, затворете Codex и го отворете отново.',
    errorRetry: 'Опитай отново',
    errorClose: 'Затвори',
  },
  "bn-BD": {
    open: "ইনকগনিটো উইন্ডো খুলুন",
    exit: "ইনকগনিটো উইন্ডো থেকে বেরোন",
    title: "ইনকগনিটো উইন্ডো",
    body: "অ্যাকাউন্ট ও সেটিংস আগের মতোই, আগের আলোচনা আসবে না। এই উইন্ডো বন্ধ করলে এবারের চ্যাটের রেকর্ড থাকবে না।",
    dismiss: "ইনকগনিটো ব্যানার বন্ধ করুন",
    errorTitle: 'ইনকগনিটো উইন্ডো খোলা যায়নি',
    errorBody: 'আবার চেষ্টা করুন। না হলে Codex বন্ধ করে আবার খুলুন।',
    errorRetry: 'আবার চেষ্টা করুন',
    errorClose: 'বন্ধ করুন',
  },
  "bs-BA": {
    open: "Otvori prozor incognito",
    exit: "Izađi iz prozora incognito",
    title: "Prozor incognito",
    body: "Račun i postavke su kao i obično, bez prethodnih razgovora. Zatvorite ovaj prozor i ovaj chat neće ostaviti zapis.",
    dismiss: "Zatvori incognito banner",
    errorTitle: 'Nije moguće otvoriti prozor incognito',
    errorBody: 'Pokušajte ponovo. Ako i dalje ne radi, zatvorite Codex i otvorite ga ponovo.',
    errorRetry: 'Pokušaj ponovo',
    errorClose: 'Zatvori',
  },
  "ca-ES": {
    open: "Obre una finestra d'incògnit",
    exit: "Surt de la finestra d'incògnit",
    title: "Finestra d'incògnit",
    body: "El compte i la configuració són els de sempre, sense converses anteriors. Si tanques aquesta finestra, aquest xat no deixarà cap registre.",
    dismiss: "Tanca el bàner d'incògnit",
    errorTitle: "No s'ha pogut obrir la finestra d'incògnit",
    errorBody: "Torna-ho a provar. Si continua fallant, surt de Codex i torna'l a obrir.",
    errorRetry: 'Torna-ho a provar',
    errorClose: 'Tanca',
  },
  "cs-CZ": {
    open: "Otevřít anonymní okno",
    exit: "Ukončit anonymní okno",
    title: "Anonymní okno",
    body: "Účet a nastavení jsou jako obvykle, bez předchozích konverzací. Po zavření tohoto okna se tento chat nezaznamená.",
    dismiss: "Zavřít banner anonymního okna",
    errorTitle: 'Anonymní okno se nepodařilo otevřít',
    errorBody: 'Zkuste to znovu. Pokud to stále nejde, ukončete Codex a otevřete ho znovu.',
    errorRetry: 'Zkusit znovu',
    errorClose: 'Zavřít',
  },
  "da-DK": {
    open: "Åbn inkognitovindue",
    exit: "Afslut inkognitovindue",
    title: "Inkognitovindue",
    body: "Konto og indstillinger er som sædvanlig, uden tidligere samtaler. Lukker du dette vindue, efterlader denne chat ingen optegnelse.",
    dismiss: "Luk inkognitobanner",
    errorTitle: 'Inkognitovinduet kunne ikke åbnes',
    errorBody: 'Prøv igen. Virker det stadig ikke, så afslut Codex og åbn det igen.',
    errorRetry: 'Prøv igen',
    errorClose: 'Luk',
  },
  "de-DE": {
    open: "Inkognito-Fenster öffnen",
    exit: "Inkognito-Fenster beenden",
    title: "Inkognito-Fenster",
    body: "Konto und Einstellungen sind wie sonst, ohne frühere Unterhaltungen. Wenn du dieses Fenster schließt, bleibt von diesem Chat kein Verlauf.",
    dismiss: "Inkognito-Banner schließen",
    errorTitle: 'Inkognito-Fenster konnte nicht geöffnet werden',
    errorBody: 'Bitte erneut versuchen. Wenn es weiterhin fehlschlägt, Codex beenden und neu öffnen.',
    errorRetry: 'Erneut versuchen',
    errorClose: 'Schließen',
  },
  "el-GR": {
    open: "Άνοιγμα παραθύρου ανώνυμης περιήγησης",
    exit: "Έξοδος από το παράθυρο ανώνυμης περιήγησης",
    title: "Παράθυρο ανώνυμης περιήγησης",
    body: "Ο λογαριασμός και οι ρυθμίσεις είναι όπως συνήθως, χωρίς προηγούμενες συνομιλίες. Κλείστε αυτό το παράθυρο και αυτή η συνομιλία δεν θα αφήσει εγγραφή.",
    dismiss: "Κλείσιμο του banner ανώνυμης περιήγησης",
    errorTitle: 'Δεν ήταν δυνατό το άνοιγμα του παραθύρου ανώνυμης περιήγησης',
    errorBody: 'Δοκιμάστε ξανά. Αν συνεχίσει να αποτυγχάνει, κλείστε το Codex και ανοίξτε το ξανά.',
    errorRetry: 'Δοκιμή ξανά',
    errorClose: 'Κλείσιμο',
  },
  "es-419": {
    open: "Abrir ventana de incógnito",
    exit: "Salir de la ventana de incógnito",
    title: "Ventana de incógnito",
    body: "La cuenta y la configuración son las de siempre, sin conversaciones anteriores. Si cierras esta ventana, este chat no dejará registro.",
    dismiss: "Cerrar el banner de incógnito",
    errorTitle: 'No se pudo abrir la ventana de incógnito',
    errorBody: 'Inténtalo de nuevo. Si sigue fallando, cierra Codex y ábrelo otra vez.',
    errorRetry: 'Reintentar',
    errorClose: 'Cerrar',
  },
  "es-ES": {
    open: "Abrir ventana de incógnito",
    exit: "Salir de la ventana de incógnito",
    title: "Ventana de incógnito",
    body: "La cuenta y la configuración son las de siempre, sin conversaciones anteriores. Si cierras esta ventana, este chat no dejará registro.",
    dismiss: "Cerrar el banner de incógnito",
    errorTitle: 'No se ha podido abrir la ventana de incógnito',
    errorBody: 'Inténtalo de nuevo. Si sigue fallando, cierra Codex y ábrelo otra vez.',
    errorRetry: 'Reintentar',
    errorClose: 'Cerrar',
  },
  "et-EE": {
    open: "Ava inkognitoaken",
    exit: "Välju inkognitoaknast",
    title: "Inkognitoaken",
    body: "Konto ja seaded on tavapärased, varasemaid vestlusi kaasa ei tooda. Kui sulged selle akna, ei jää sellest vestlusest jälge.",
    dismiss: "Sulge inkognitobänner",
    errorTitle: 'Inkognitoakent ei saanud avada',
    errorBody: 'Proovi uuesti. Kui ikka ei õnnestu, sulge Codex ja ava see uuesti.',
    errorRetry: 'Proovi uuesti',
    errorClose: 'Sulge',
  },  fa: {
    open: "باز کردن پنجره ناشناس",
    exit: "خروج از پنجره ناشناس",
    title: "پنجره ناشناس",
    body: "حساب و تنظیمات مثل همیشه است و گفتگوهای قبلی وارد نمی‌شود. با بستن این پنجره، این گفتگو ثبت نمی‌ماند.",
    dismiss: "بستن بنر پنجره ناشناس",
    errorTitle: 'پنجره ناشناس باز نشد',
    errorBody: 'دوباره امتحان کنید. اگر باز هم نشد، Codex را ببندید و دوباره باز کنید.',
    errorRetry: 'تلاش دوباره',
    errorClose: 'بستن',
  },
  "fi-FI": {
    open: "Avaa incognito-ikkuna",
    exit: "Poistu incognito-ikkunasta",
    title: "Incognito-ikkuna",
    body: "Tili ja asetukset ovat ennallaan, aiempia keskusteluja ei tuoda. Jos suljet tämän ikkunan, tästä chatista ei jää merkintää.",
    dismiss: "Sulje incognito-banneri",
    errorTitle: 'Incognito-ikkunaa ei voitu avata',
    errorBody: 'Yritä uudelleen. Jos se ei vieläkään onnistu, sulje Codex ja avaa se uudestaan.',
    errorRetry: 'Yritä uudelleen',
    errorClose: 'Sulje',
  },
  "fr-CA": {
    open: "Ouvrir une fenêtre de navigation privée",
    exit: "Quitter la fenêtre de navigation privée",
    title: "Fenêtre de navigation privée",
    body: "Le compte et les réglages sont les mêmes qu’à l’habitude, sans les conversations précédentes. Fermez cette fenêtre et ce clavardage ne laissera aucune trace.",
    dismiss: "Fermer la bannière de navigation privée",
    errorTitle: 'Impossible d’ouvrir la fenêtre de navigation privée',
    errorBody: 'Réessayez. Si ça échoue encore, quittez Codex puis rouvrez-le.',
    errorRetry: 'Réessayer',
    errorClose: 'Fermer',
  },
  "fr-FR": {
    open: "Ouvrir une fenêtre de navigation privée",
    exit: "Quitter la fenêtre de navigation privée",
    title: "Fenêtre de navigation privée",
    body: "Le compte et les paramètres sont les mêmes que d’habitude, sans les conversations précédentes. Fermez cette fenêtre et cette discussion ne laissera aucune trace.",
    dismiss: "Fermer la bannière de navigation privée",
    errorTitle: 'Impossible d’ouvrir la fenêtre de navigation privée',
    errorBody: 'Réessayez. Si cela échoue encore, quittez Codex puis rouvrez-le.',
    errorRetry: 'Réessayer',
    errorClose: 'Fermer',
  },
  "gu-IN": {
    open: "ઇનકોગ્નિટો વિન્ડો ખોલો",
    exit: "ઇનકોગ્નિટો વિન્ડોમાંથી બહાર નીકળો",
    title: "ઇનકોગ્નિટો વિન્ડો",
    body: "એકાઉન્ટ અને સેટિંગ્સ હંમેશની જેમ છે, અગાઉની વાતચીતો આવશે નહીં. આ વિન્ડો બંધ કરશો તો આ ચેટનો રેકોર્ડ રહેશે નહીં.",
    dismiss: "ઇનકોગ્નિટો બેનર બંધ કરો",
    errorTitle: 'ઇનકોગ્નિટો વિન્ડો ખોલી શકાઈ નહીં',
    errorBody: 'ફરી પ્રયાસ કરો. હજુ ન થાય તો Codex બંધ કરીને ફરી ખોલો.',
    errorRetry: 'ફરી પ્રયાસ કરો',
    errorClose: 'બંધ કરો',
  },
  "hi-IN": {
    open: "गुप्त विंडो खोलें",
    exit: "गुप्त विंडो से बाहर निकलें",
    title: "गुप्त विंडो",
    body: "खाता और सेटिंग्स वैसे ही हैं, पिछली बातचीत नहीं आएगी। यह विंडो बंद करने पर इस चैट का रिकॉर्ड नहीं रहेगा।",
    dismiss: "गुप्त विंडो बैनर बंद करें",
    errorTitle: 'गुप्त विंडो नहीं खुल सकी',
    errorBody: 'फिर कोशिश करें। अगर फिर भी न खुले, तो Codex बंद करके फिर खोलें।',
    errorRetry: 'फिर कोशिश करें',
    errorClose: 'बंद करें',
  },
  "hr-HR": {
    open: "Otvori prozor incognito",
    exit: "Izađi iz prozora incognito",
    title: "Prozor incognito",
    body: "Račun i postavke su kao i obično, bez prethodnih razgovora. Zatvorite ovaj prozor i ovaj chat neće ostaviti zapis.",
    dismiss: "Zatvori incognito banner",
    errorTitle: 'Nije moguće otvoriti prozor incognito',
    errorBody: 'Pokušajte ponovo. Ako i dalje ne radi, zatvorite Codex i otvorite ga ponovo.',
    errorRetry: 'Pokušaj ponovo',
    errorClose: 'Zatvori',
  },
  "hu-HU": {
    open: "Inkognitóablak megnyitása",
    exit: "Kilépés az inkognitóablakból",
    title: "Inkognitóablak",
    body: "A fiók és a beállítások a szokásosak, korábbi beszélgetések nélkül. Ha bezárod ezt az ablakot, ebből a csevegésből nem marad nyom.",
    dismiss: "Inkognitó banner bezárása",
    errorTitle: 'Nem sikerült megnyitni az inkognitóablakot',
    errorBody: 'Próbáld újra. Ha továbbra sem megy, zárd be a Codexet, majd nyisd meg újra.',
    errorRetry: 'Újra',
    errorClose: 'Bezárás',
  },
  "hy-AM": {
    open: "Բացել գաղտնի պատուհանը",
    exit: "Դուրս գալ գաղտնի պատուհանից",
    title: "Գաղտնի պատուհան",
    body: "Հաշիվն ու կարգավորումները սովորականի պես են, նախորդ զրույցները չեն բերվի։ Այս պատուհանը փակելիս այս զրույցը գրառում չի թողնի։",
    dismiss: "Փակել գաղտնի պատուհանի դրոշակը",
    errorTitle: 'Չհաջողվեց բացել գաղտնի պատուհանը',
    errorBody: 'Կրկին փորձեք։ Եթե դեռ չի ստացվում, փակեք Codex-ը և նորից բացեք։',
    errorRetry: 'Կրկին փորձել',
    errorClose: 'Փակել',
  },
  "id-ID": {
    open: "Buka jendela penyamaran",
    exit: "Keluar dari jendela penyamaran",
    title: "Jendela penyamaran",
    body: "Akun dan pengaturan sama seperti biasa, tanpa percakapan sebelumnya. Tutup jendela ini dan obrolan ini tidak akan meninggalkan catatan.",
    dismiss: "Tutup banner jendela penyamaran",
    errorTitle: 'Tidak dapat membuka jendela penyamaran',
    errorBody: 'Coba lagi. Jika masih gagal, keluar dari Codex lalu buka lagi.',
    errorRetry: 'Coba lagi',
    errorClose: 'Tutup',
  },
  "is-IS": {
    open: "Opna huliðsglugga",
    exit: "Hætta í huliðsglugga",
    title: "Huliðsgluggi",
    body: "Aðgangur og stillingar eru eins og venjulega, án fyrri spjalla. Ef þú lokar þessum glugga skilur þetta spjall ekkert eftir sig.",
    dismiss: "Loka huliðsbanneri",
    errorTitle: 'Gat ekki opnað huliðsglugga',
    errorBody: 'Reyndu aftur. Ef það mistakast enn, lokaðu Codex og opnaðu aftur.',
    errorRetry: 'Reyna aftur',
    errorClose: 'Loka',
  },
  "it-IT": {
    open: "Apri finestra in incognito",
    exit: "Esci dalla finestra in incognito",
    title: "Finestra in incognito",
    body: "Account e impostazioni sono quelli di sempre, senza le chat precedenti. Chiudi questa finestra e questa conversazione non lascerà traccia.",
    dismiss: "Chiudi il banner in incognito",
    errorTitle: 'Impossibile aprire la finestra in incognito',
    errorBody: 'Riprova. Se continua a non funzionare, chiudi Codex e aprilo di nuovo.',
    errorRetry: 'Riprova',
    errorClose: 'Chiudi',
  },
  "ja-JP": {
    open: "シークレットウィンドウを開く",
    exit: "シークレットウィンドウを終了",
    title: "シークレットウィンドウ",
    body: "アカウントと設定は普段と同じで、以前の会話は引き継ぎません。このウィンドウを閉じると、今回のチャットは残りません。",
    dismiss: "シークレットウィンドウのバナーを閉じる",
    errorTitle: 'シークレットウィンドウを開けませんでした',
    errorBody: 'もう一度お試しください。まだ開かない場合は、Codex を終了してから開き直してください。',
    errorRetry: '再試行',
    errorClose: '閉じる',
  },
  "ka-GE": {
    open: "ინკოგნიტო ფანჯრის გახსნა",
    exit: "ინკოგნიტო ფანჯრიდან გასვლა",
    title: "ინკოგნიტო ფანჯარა",
    body: "ანგარიში და პარამეტრები ჩვეულებრივია, წინა საუბრები არ შემოვა. ამ ფანჯრის დახურვის შემდეგ ეს ჩატი ჩანაწერს არ დატოვებს.",
    dismiss: "ინკოგნიტო ბანერის დახურვა",
    errorTitle: 'ინკოგნიტო ფანჯარა ვერ გაიხსნა',
    errorBody: 'სცადეთ თავიდან. თუ ისევ ვერ გაიხსნა, დახურეთ Codex და გახსენით ხელახლა.',
    errorRetry: 'თავიდან ცდა',
    errorClose: 'დახურვა',
  },  kk: {
    open: "Инкогнито терезесін ашу",
    exit: "Инкогнито терезесінен шығу",
    title: "Инкогнито терезесі",
    body: "Тіркелгі мен баптаулар әдеттегідей, бұрынғы әңгімелер кірмейді. Бұл терезені жапсаңыз, осы чат жазба қалдырмайды.",
    dismiss: "Инкогнито баннерін жабу",
    errorTitle: 'Инкогнито терезесі ашылмады',
    errorBody: 'Қайта көріңіз. Әлі де болмаса, Codex-ті жауып, қайта ашыңыз.',
    errorRetry: 'Қайталау',
    errorClose: 'Жабу',
  },
  "kn-IN": {
    open: "ಅಜ್ಞಾತ ವಿಂಡೋ ತೆರೆಯಿರಿ",
    exit: "ಅಜ್ಞಾತ ವಿಂಡೋದಿಂದ ನಿರ್ಗಮಿಸಿ",
    title: "ಅಜ್ಞಾತ ವಿಂಡೋ",
    body: "ಖಾತೆ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಎಂದಿನಂತೆ, ಹಿಂದಿನ ಸಂಭಾಷಣೆಗಳು ಬರುವುದಿಲ್ಲ. ಈ ವಿಂಡೋ ಮುಚ್ಚಿದರೆ ಈ ಚಾಟ್‌ನ ದಾಖಲೆ ಉಳಿಯುವುದಿಲ್ಲ.",
    dismiss: "ಅಜ್ಞಾತ ಬ್ಯಾನರ್ ಮುಚ್ಚಿ",
    errorTitle: 'ಅಜ್ಞಾತ ವಿಂಡೋ ತೆರೆಯಲಾಗಲಿಲ್ಲ',
    errorBody: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ. ಇನ್ನೂ ಆಗದಿದ್ದರೆ Codex ಮುಚ್ಚಿ ಮತ್ತೆ ತೆರೆಯಿರಿ.',
    errorRetry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    errorClose: 'ಮುಚ್ಚಿ',
  },
  "ko-KR": {
    open: "시크릿 창 열기",
    exit: "시크릿 창 나가기",
    title: "시크릿 창",
    body: "계정과 설정은 평소와 같고, 이전 대화는 가져오지 않습니다. 창을 닫으면 이번 채팅은 남지 않습니다.",
    dismiss: "시크릿 창 배너 닫기",
    errorTitle: '시크릿 창을 열 수 없습니다',
    errorBody: '다시 시도하세요. 그래도 안 되면 Codex를 종료한 뒤 다시 여세요.',
    errorRetry: '다시 시도',
    errorClose: '닫기',
  },  lt: {
    open: "Atidaryti inkognito langą",
    exit: "Išeiti iš inkognito lango",
    title: "Inkognito langas",
    body: "Paskyra ir nustatymai tokie patys kaip įprastai, ankstesni pokalbiai neperkeliami. Užvėrus šį langą šis pokalbis nepaliks įrašo.",
    dismiss: "Uždaryti inkognito juostą",
    errorTitle: 'Nepavyko atidaryti inkognito lango',
    errorBody: 'Bandykite dar kartą. Jei vis tiek nepavyksta, uždarykite Codex ir atidarykite iš naujo.',
    errorRetry: 'Bandyti dar kartą',
    errorClose: 'Uždaryti',
  },
  "lv-LV": {
    open: "Atvērt inkognito logu",
    exit: "Iziet no inkognito loga",
    title: "Inkognito logs",
    body: "Konts un iestatījumi ir kā parasti, bez iepriekšējām sarunām. Aizverot šo logu, šī tērzēšana neatstās ierakstu.",
    dismiss: "Aizvērt inkognito baneri",
    errorTitle: 'Neizdevās atvērt inkognito logu',
    errorBody: 'Mēģiniet vēlreiz. Ja joprojām neizdodas, aizveriet Codex un atveriet to no jauna.',
    errorRetry: 'Mēģināt vēlreiz',
    errorClose: 'Aizvērt',
  },
  "mk-MK": {
    open: "Отвори прозорец инкогнито",
    exit: "Излези од прозорецот инкогнито",
    title: "Прозорец инкогнито",
    body: "Сметката и поставките се како и обично, без претходни разговори. Ако го затворите овој прозорец, овој разговор нема да остави запис.",
    dismiss: "Затвори го банерот за инкогнито",
    errorTitle: 'Не можеше да се отвори прозорецот инкогнито',
    errorBody: 'Обидете се повторно. Ако пак не успее, затворете го Codex и отворете го повторно.',
    errorRetry: 'Обиди се повторно',
    errorClose: 'Затвори',
  },  ml: {
    open: "ഇൻകോഗ്നിറ്റോ വിൻഡോ തുറക്കുക",
    exit: "ഇൻകോഗ്നിറ്റോ വിൻഡോയിൽ നിന്ന് പുറത്തുകടക്കുക",
    title: "ഇൻകോഗ്നിറ്റോ വിൻഡോ",
    body: "അക്കൗണ്ടും ക്രമീകരണങ്ങളും പതിവുപോലെയാണ്, മുമ്പത്തെ സംഭാഷണങ്ങൾ വരില്ല. ഈ വിൻഡോ അടച്ചാൽ ഈ ചാറ്റിന്റെ രേഖ നിലനിൽക്കില്ല.",
    dismiss: "ഇൻകോഗ്നിറ്റോ ബാനർ അടയ്ക്കുക",
    errorTitle: 'ഇൻകോഗ്നിറ്റോ വിൻഡോ തുറക്കാനായില്ല',
    errorBody: 'വീണ്ടും ശ്രമിക്കുക. ഇനിയും ആയില്ലെങ്കിൽ Codex അടച്ച് വീണ്ടും തുറക്കുക.',
    errorRetry: 'വീണ്ടും ശ്രമിക്കുക',
    errorClose: 'അടയ്ക്കുക',
  },  mn: {
    open: "Нууц цонх нээх",
    exit: "Нууц цонхноос гарах",
    title: "Нууц цонх",
    body: "Бүртгэл, тохиргоо хэвийнхээ л адил, өмнөх яриа орж ирэхгүй. Энэ цонхыг хаавал энэ чат үлдэхгүй.",
    dismiss: "Нууц цонхны баннерыг хаах",
    errorTitle: 'Нууц цонх нээгдсэнгүй',
    errorBody: 'Дахин оролдоно уу. Хэрэв дахин бүтэхгүй бол Codex-ийг хаагаад дахин нээнэ үү.',
    errorRetry: 'Дахин оролдох',
    errorClose: 'Хаах',
  },
  "mr-IN": {
    open: "गुप्त विंडो उघडा",
    exit: "गुप्त विंडोमधून बाहेर पडा",
    title: "गुप्त विंडो",
    body: "खाते आणि सेटिंग्ज नेहमीप्रमाणे आहेत, आधीच्या संभाषणांचा समावेश होणार नाही. हे विंडो बंद केल्यावर या चॅटची नोंद राहणार नाही.",
    dismiss: "गुप्त बॅनर बंद करा",
    errorTitle: 'गुप्त विंडो उघडता आली नाही',
    errorBody: 'पुन्हा प्रयत्न करा. तरी न झाल्यास Codex बंद करून पुन्हा उघडा.',
    errorRetry: 'पुन्हा प्रयत्न करा',
    errorClose: 'बंद करा',
  },
  "ms-MY": {
    open: "Buka tetingkap inkognito",
    exit: "Keluar dari tetingkap inkognito",
    title: "Tetingkap inkognito",
    body: "Akaun dan tetapan sama seperti biasa, tanpa perbualan terdahulu. Tutup tetingkap ini dan sembang ini tidak akan meninggalkan rekod.",
    dismiss: "Tutup sepanduk inkognito",
    errorTitle: 'Tidak dapat membuka tetingkap inkognito',
    errorBody: 'Cuba lagi. Jika masih gagal, tutup Codex lalu buka semula.',
    errorRetry: 'Cuba lagi',
    errorClose: 'Tutup',
  },
  "my-MM": {
    open: "လျှို့ဝှက်ဝင်းဒိုးဖွင့်ရန်",
    exit: "လျှို့ဝှက်ဝင်းဒိုးမှ ထွက်ရန်",
    title: "လျှို့ဝှက်ဝင်းဒိုး",
    body: "အကောင့်နှင့် ဆက်တင်များသည် ပုံမှန်အတိုင်းဖြစ်ပြီး ယခင်စကားဝိုင်းများ မပါဝင်ပါ။ ဤဝင်းဒိုးကို ပိတ်လိုက်လျှင် ဤချတ်မှတ်တမ်း ကျန်မည်မဟုတ်ပါ။",
    dismiss: "လျှို့ဝှက်နဖူးစည်းကို ပိတ်ရန်",
    errorTitle: 'လျှို့ဝှက်ဝင်းဒိုး ဖွင့်မရပါ',
    errorBody: 'ထပ်ကြိုးစားပါ။ မရသေးရင် Codex ကို ပိတ်ပြီး ပြန်ဖွင့်ပါ။',
    errorRetry: 'ထပ်ကြိုးစားရန်',
    errorClose: 'ပိတ်ရန်',
  },
  "nb-NO": {
    open: "Åpne inkognitovindu",
    exit: "Avslutt inkognitovindu",
    title: "Inkognitovindu",
    body: "Konto og innstillinger er som vanlig, uten tidligere samtaler. Lukker du dette vinduet, etterlater ikke denne chatten noen oppføring.",
    dismiss: "Lukk inkognitobanneret",
    errorTitle: 'Kunne ikke åpne inkognitovinduet',
    errorBody: 'Prøv igjen. Hvis det fortsatt feiler, avslutt Codex og åpne det på nytt.',
    errorRetry: 'Prøv igjen',
    errorClose: 'Lukk',
  },
  "nl-NL": {
    open: "Incognitovenster openen",
    exit: "Incognitovenster sluiten",
    title: "Incognitovenster",
    body: "Account en instellingen zijn hetzelfde als anders, zonder eerdere gesprekken. Sluit dit venster en deze chat laat geen record achter.",
    dismiss: "Incognitobanner sluiten",
    errorTitle: 'Incognitovenster kon niet worden geopend',
    errorBody: 'Probeer het opnieuw. Lukt het nog niet, sluit Codex en open het opnieuw.',
    errorRetry: 'Opnieuw proberen',
    errorClose: 'Sluiten',
  },  pa: {
    open: "ਇਨਕੌਗਨੀਟੋ ਵਿੰਡੋ ਖੋਲ੍ਹੋ",
    exit: "ਇਨਕੌਗਨੀਟੋ ਵਿੰਡੋ ਤੋਂ ਬਾਹਰ ਜਾਓ",
    title: "ਇਨਕੌਗਨੀਟੋ ਵਿੰਡੋ",
    body: "ਖਾਤਾ ਅਤੇ ਸੈਟਿੰਗਾਂ ਆਮ ਵਾਂਗ ਹਨ, ਪਿਛਲੀਆਂ ਗੱਲਾਂ ਨਹੀਂ ਆਉਣਗੀਆਂ। ਇਹ ਵਿੰਡੋ ਬੰਦ ਕਰਨ ਤੇ ਇਸ ਚੈਟ ਦਾ ਰਿਕਾਰਡ ਨਹੀਂ ਰਹੇਗਾ।",
    dismiss: "ਇਨਕੌਗਨੀਟੋ ਬੈਨਰ ਬੰਦ ਕਰੋ",
    errorTitle: 'ਇਨਕੌਗਨੀਟੋ ਵਿੰਡੋ ਨਹੀਂ ਖੁੱਲ੍ਹੀ',
    errorBody: 'ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ। ਫਿਰ ਵੀ ਨਾ ਖੁੱਲ੍ਹੇ ਤਾਂ Codex ਬੰਦ ਕਰਕੇ ਮੁੜ ਖੋਲ੍ਹੋ।',
    errorRetry: 'ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    errorClose: 'ਬੰਦ ਕਰੋ',
  },
  "pl-PL": {
    open: "Otwórz okno incognito",
    exit: "Zamknij okno incognito",
    title: "Okno incognito",
    body: "Konto i ustawienia są jak zwykle, bez wcześniejszych rozmów. Zamknij to okno, a ta rozmowa nie pozostawi zapisu.",
    dismiss: "Zamknij baner incognito",
    errorTitle: 'Nie udało się otworzyć okna incognito',
    errorBody: 'Spróbuj ponownie. Jeśli nadal nie działa, zamknij Codex i otwórz go znowu.',
    errorRetry: 'Spróbuj ponownie',
    errorClose: 'Zamknij',
  },
  "pt-BR": {
    open: "Abrir janela anônima",
    exit: "Sair da janela anônima",
    title: "Janela anônima",
    body: "A conta e as configurações são as de sempre, sem conversas anteriores. Feche esta janela e este chat não deixará registro.",
    dismiss: "Fechar o banner da janela anônima",
    errorTitle: 'Não foi possível abrir a janela anônima',
    errorBody: 'Tente de novo. Se ainda falhar, saia do Codex e abra novamente.',
    errorRetry: 'Tentar de novo',
    errorClose: 'Fechar',
  },
  "pt-PT": {
    open: "Abrir janela de navegação privada",
    exit: "Sair da janela de navegação privada",
    title: "Janela de navegação privada",
    body: "A conta e as definições são as do costume, sem conversas anteriores. Feche esta janela e esta conversa não deixará registo.",
    dismiss: "Fechar o banner de navegação privada",
    errorTitle: 'Não foi possível abrir a janela de navegação privada',
    errorBody: 'Tente novamente. Se continuar a falhar, saia do Codex e volte a abri-lo.',
    errorRetry: 'Tentar novamente',
    errorClose: 'Fechar',
  },
  "ro-RO": {
    open: "Deschide fereastra incognito",
    exit: "Ieși din fereastra incognito",
    title: "Fereastră incognito",
    body: "Contul și setările sunt ca de obicei, fără conversațiile anterioare. Dacă închizi această fereastră, acest chat nu va lăsa nicio înregistrare.",
    dismiss: "Închide bannerul incognito",
    errorTitle: 'Nu s-a putut deschide fereastra incognito',
    errorBody: 'Încearcă din nou. Dacă tot nu merge, închide Codex și deschide-l din nou.',
    errorRetry: 'Încearcă din nou',
    errorClose: 'Închide',
  },
  "ru-RU": {
    open: "Открыть окно инкогнито",
    exit: "Выйти из окна инкогнито",
    title: "Окно инкогнито",
    body: "Аккаунт и настройки как обычно, без прошлых диалогов. Закройте это окно — и этот чат не оставит записи.",
    dismiss: "Закрыть баннер окна инкогнито",
    errorTitle: 'Не удалось открыть окно инкогнито',
    errorBody: 'Попробуйте ещё раз. Если снова не получится, закройте Codex и откройте его заново.',
    errorRetry: 'Повторить',
    errorClose: 'Закрыть',
  },
  "sk-SK": {
    open: "Otvoriť anonymné okno",
    exit: "Ukončiť anonymné okno",
    title: "Anonymné okno",
    body: "Účet a nastavenia sú ako zvyčajne, bez predchádzajúcich konverzácií. Ak toto okno zatvoríte, tento chat nezanechá záznam.",
    dismiss: "Zavrieť banner anonymného okna",
    errorTitle: 'Anonymné okno sa nepodarilo otvoriť',
    errorBody: 'Skúste znova. Ak to stále nejde, ukončite Codex a otvorte ho znova.',
    errorRetry: 'Skúsiť znova',
    errorClose: 'Zavrieť',
  },
  "sl-SI": {
    open: "Odpri okno brez beleženja",
    exit: "Zapusti okno brez beleženja",
    title: "Okno brez beleženja",
    body: "Račun in nastavitve so kot običajno, brez prejšnjih pogovorov. Če zaprete to okno, ta klepet ne pusti zapisa.",
    dismiss: "Zapri pasico okna brez beleženja",
    errorTitle: 'Okna brez beleženja ni bilo mogoče odpreti',
    errorBody: 'Poskusite znova. Če še vedno ne deluje, zaprite Codex in ga znova odprite.',
    errorRetry: 'Poskusi znova',
    errorClose: 'Zapri',
  },
  "so-SO": {
    open: "Fur daaqadda qarsoodiga",
    exit: "Ka bax daaqadda qarsoodiga",
    title: "Daaqadda qarsoodiga",
    body: "Akoonka iyo dejinta waa sidii caadiga ahayd, wadahadalladii hore ma imanayaan. Daaqaddan xir, sheekadani ma reebi doonto diiwaan.",
    dismiss: "Xir calanka daaqadda qarsoodiga",
    errorTitle: 'Daaqadda qarsoodiga lama furi karin',
    errorBody: 'Isku day mar kale. Haddii weli ay fashilanto, xir Codex ka dibna fur.',
    errorRetry: 'Isku day mar kale',
    errorClose: 'Xir',
  },
  "sq-AL": {
    open: "Hap dritaren inkognito",
    exit: "Dil nga dritarja inkognito",
    title: "Dritare inkognito",
    body: "Llogaria dhe cilësimet janë si zakonisht, pa bisedat e mëparshme. Mbylleni këtë dritare dhe ky bisedim nuk do të lërë regjistër.",
    dismiss: "Mbyll banderolën inkognito",
    errorTitle: 'Nuk u hap dritarja inkognito',
    errorBody: 'Provo sërish. Nëse prapë dështon, mbyll Codex dhe hapë përsëri.',
    errorRetry: 'Provo sërish',
    errorClose: 'Mbyll',
  },
  "sr-RS": {
    open: "Отвори прозор инкогнито",
    exit: "Изађи из прозора инкогнито",
    title: "Прозор инкогнито",
    body: "Налог и подешавања су као обично, без претходних разговора. Ако затворите овај прозор, овај ћаскање неће оставити запис.",
    dismiss: "Затвори банер инкогнито",
    errorTitle: 'Није могуће отворити прозор инкогнито',
    errorBody: 'Покушајте поново. Ако и даље не ради, затворите Codex и отворите га поново.',
    errorRetry: 'Покушај поново',
    errorClose: 'Затвори',
  },
  "sv-SE": {
    open: "Öppna inkognitofönster",
    exit: "Avsluta inkognitofönster",
    title: "Inkognitofönster",
    body: "Konto och inställningar är som vanligt, utan tidigare samtal. Stänger du det här fönstret lämnar den här chatten ingen post.",
    dismiss: "Stäng inkognitobannern",
    errorTitle: 'Kunde inte öppna inkognitofönstret',
    errorBody: 'Försök igen. Om det fortfarande inte går, avsluta Codex och öppna det igen.',
    errorRetry: 'Försök igen',
    errorClose: 'Stäng',
  },
  "sw-TZ": {
    open: "Fungua dirisha la faragha",
    exit: "Toka kwenye dirisha la faragha",
    title: "Dirisha la faragha",
    body: "Akaunti na mipangilio ni kama kawaida, bila mazungumzo ya awali. Funga dirisha hili na gumzo hili halitaacha rekodi.",
    dismiss: "Funga bango la dirisha la faragha",
    errorTitle: 'Imeshindwa kufungua dirisha la faragha',
    errorBody: 'Jaribu tena. Ikiwa bado itashindwa, funga Codex kisha uifungue tena.',
    errorRetry: 'Jaribu tena',
    errorClose: 'Funga',
  },
  "ta-IN": {
    open: "மறைநிலை சாளரத்தைத் திற",
    exit: "மறைநிலை சாளரத்திலிருந்து வெளியேறு",
    title: "மறைநிலை சாளரம்",
    body: "கணக்கும் அமைப்புகளும் வழக்கம் போலவே; முந்தைய உரையாடல்கள் வராது. இந்தச் சாளரத்தை மூடினால் இந்த அரட்டையின் பதிவு இருக்காது.",
    dismiss: "மறைநிலை பதாகையை மூடு",
    errorTitle: 'மறைநிலை சாளரத்தைத் திறக்க முடியவில்லை',
    errorBody: 'மீண்டும் முயலவும். இன்னும் திறக்கவில்லை என்றால் Codex-ஐ மூடி மீண்டும் திறக்கவும்.',
    errorRetry: 'மீண்டும் முயலவும்',
    errorClose: 'மூடு',
  },
  "te-IN": {
    open: "అజ్ఞాత విండోను తెరవండి",
    exit: "అజ్ఞాత విండో నుంచి నిష్క్రమించండి",
    title: "అజ్ఞాత విండో",
    body: "ఖాతా, సెట్టింగ్‌లు ఎప్పటిలాగే ఉంటాయి; మునుపటి సంభాషణలు రావు. ఈ విండో మూస్తే ఈ చాట్ రికార్డు ఉండదు.",
    dismiss: "అజ్ఞాత బ్యానర్‌ను మూసివేయండి",
    errorTitle: 'అజ్ఞాత విండో తెరవలేకపోయాం',
    errorBody: 'మళ్లీ ప్రయత్నించండి. ఇంకా కాకపోతే Codex ను మూసి మళ్లీ తెరవండి.',
    errorRetry: 'మళ్లీ ప్రయత్నించండి',
    errorClose: 'మూసివేయి',
  },
  "th-TH": {
    open: "เปิดหน้าต่างไม่ระบุตัวตน",
    exit: "ออกจากหน้าต่างไม่ระบุตัวตน",
    title: "หน้าต่างไม่ระบุตัวตน",
    body: "บัญชีและการตั้งค่าเหมือนเดิม จะไม่ดึงบทสนทนาก่อนหน้า ปิดหน้าต่างนี้แล้วแชทนี้จะไม่เหลือบันทึก",
    dismiss: "ปิดแบนเนอร์หน้าต่างไม่ระบุตัวตน",
    errorTitle: 'เปิดหน้าต่างไม่ระบุตัวตนไม่ได้',
    errorBody: 'ลองอีกครั้ง หากยังไม่ได้ ให้ปิด Codex แล้วเปิดใหม่',
    errorRetry: 'ลองอีกครั้ง',
    errorClose: 'ปิด',
  },  tl: {
    open: "Buksan ang incognito window",
    exit: "Lumabas sa incognito window",
    title: "Incognito window",
    body: "Pareho pa rin ang account at settings, walang dating usapan. Isara ang window na ito at hindi mag-iiwan ng record ang chat na ito.",
    dismiss: "Isara ang incognito banner",
    errorTitle: 'Hindi mabuksan ang incognito window',
    errorBody: 'Subukan ulit. Kung hindi pa rin, isara ang Codex at buksan ulit.',
    errorRetry: 'Subukan ulit',
    errorClose: 'Isara',
  },
  "tr-TR": {
    open: "Gizli pencere aç",
    exit: "Gizli pencereden çık",
    title: "Gizli pencere",
    body: "Hesap ve ayarlar her zamanki gibi; önceki sohbetler gelmez. Bu pencereyi kapatırsanız bu sohbet kayıt bırakmaz.",
    dismiss: "Gizli pencere banner’ını kapat",
    errorTitle: 'Gizli pencere açılamadı',
    errorBody: 'Yeniden deneyin. Hâlâ açılmazsa Codex’i kapatıp tekrar açın.',
    errorRetry: 'Yeniden dene',
    errorClose: 'Kapat',
  },
  "uk-UA": {
    open: "Відкрити вікно інкогніто",
    exit: "Вийти з вікна інкогніто",
    title: "Вікно інкогніто",
    body: "Обліковий запис і налаштування як завжди, без попередніх розмов. Закрийте це вікно — і цей чат не залишить запису.",
    dismiss: "Закрити банер вікна інкогніто",
    errorTitle: 'Не вдалося відкрити вікно інкогніто',
    errorBody: 'Спробуйте ще раз. Якщо знову не вийде, закрийте Codex і відкрийте його знову.',
    errorRetry: 'Спробувати ще раз',
    errorClose: 'Закрити',
  },  ur: {
    open: "خفیہ ونڈو کھولیں",
    exit: "خفیہ ونڈو سے باہر نکلیں",
    title: "خفیہ ونڈو",
    body: "اکاؤنٹ اور سیٹنگز ویسی ہی ہیں، پچھلی گفتگو نہیں آئے گی۔ یہ ونڈو بند کرنے پر اس چیٹ کا ریکارڈ نہیں رہے گا۔",
    dismiss: "خفیہ بینر بند کریں",
    errorTitle: 'خفیہ ونڈو نہیں کھل سکی',
    errorBody: 'دوبارہ کوشش کریں۔ پھر بھی نہ کھلے تو Codex بند کر کے دوبارہ کھولیں۔',
    errorRetry: 'دوبارہ کوشش کریں',
    errorClose: 'بند کریں',
  },
  "vi-VN": {
    open: "Mở cửa sổ ẩn danh",
    exit: "Thoát cửa sổ ẩn danh",
    title: "Cửa sổ ẩn danh",
    body: "Tài khoản và cài đặt như bình thường, không mang theo hội thoại cũ. Đóng cửa sổ này thì cuộc trò chuyện này sẽ không để lại bản ghi.",
    dismiss: "Đóng banner cửa sổ ẩn danh",
    errorTitle: 'Không mở được cửa sổ ẩn danh',
    errorBody: 'Thử lại. Nếu vẫn không được, hãy thoát Codex rồi mở lại.',
    errorRetry: 'Thử lại',
    errorClose: 'Đóng',
  },
};
