// Short, purpose-specific copy for the current official app. Keep one entry
// for every locale in ACCESSIBILITY_SETUP_COPY; this is not an install reason.
export const ACCESSIBILITY_OFFICIAL_COPY: Readonly<Record<string, string>> = {
  am: "ይህ ይፋዊው ChatGPT መተግበሪያ ነው። የስክሪፕት ቁጥጥርን ለመመለስ በስርዓት ቅንብሮች ውስጥ የተደራሽነት ፈቃድ ይስጡት።",
  ar: "هذا هو تطبيق ChatGPT الرسمي. اسمح له في إعدادات النظام باستخدام إمكانية الوصول لاستعادة التحكم في البرامج النصية.",
  "bg-BG": "Това е официалното приложение ChatGPT. Разрешете му достъп до Улеснен достъп в Системни настройки, за да възстановите управлението на скриптове.",
  "bn-BD": "এটি অফিসিয়াল ChatGPT অ্যাপ। স্ক্রিপ্ট নিয়ন্ত্রণ ফিরে পেতে সিস্টেম সেটিংসে এটিকে অ্যাক্সেসিবিলিটির অনুমতি দিন।",
  "bs-BA": "Ovo je zvanična aplikacija ChatGPT. Dozvolite joj pristup pristupačnosti u sistemskim postavkama da biste vratili kontrolu skriptama.",
  "ca-ES": "Aquesta és l’app oficial de ChatGPT. Permet-ne l’accés a l’accessibilitat a la configuració del sistema per recuperar el control dels scripts.",
  "cs-CZ": "Toto je oficiální aplikace ChatGPT. Povolte jí v Nastavení systému přístup ke Zpřístupnění, abyste obnovili ovládání skriptů.",
  "da-DK": "Dette er den officielle ChatGPT-app. Giv den adgang til Tilgængelighed i Systemindstillinger for at gendanne scriptstyring.",
  "de-DE": "Dies ist die offizielle ChatGPT-App. Erlaube ihr in den Systemeinstellungen den Zugriff auf Bedienungshilfen, um die Skriptsteuerung wiederherzustellen.",
  "el-GR": "Αυτή είναι η επίσημη εφαρμογή ChatGPT. Επιτρέψτε της την Πρόσβαση στις Ρυθμίσεις συστήματος για να επαναφέρετε τον έλεγχο σεναρίων.",
  "es-419": "Esta es la app oficial de ChatGPT. Permítele el acceso a Accesibilidad en Configuración del Sistema para restaurar el control de scripts.",
  "es-ES": "Esta es la app oficial de ChatGPT. Permítele el acceso a Accesibilidad en Ajustes del Sistema para restaurar el control de scripts.",
  "et-EE": "See on ametlik ChatGPT rakendus. Skriptijuhtimise taastamiseks luba sellele süsteemiseadetes juurdepääs hõlbustusfunktsioonidele.",
  fa: "این برنامه رسمی ChatGPT است. برای بازگرداندن کنترل اسکریپت، در تنظیمات سیستم اجازهٔ دسترسی‌پذیری را به آن بدهید.",
  "fi-FI": "Tämä on virallinen ChatGPT-appi. Palauta komentosarjojen hallinta sallimalla sille Käyttöapu-järjestelmäasetuksissa.",
  "fr-CA": "Il s’agit de l’app officielle ChatGPT. Autorisez-la dans Réglages Système à accéder à l’accessibilité pour rétablir le contrôle des scripts.",
  "fr-FR": "Il s’agit de l’app officielle ChatGPT. Autorisez-la dans Réglages Système à accéder à l’accessibilité pour rétablir le contrôle des scripts.",
  "gu-IN": "આ સત્તાવાર ChatGPT ઍપ છે. સ્ક્રિપ્ટ નિયંત્રણ પુનઃસ્થાપિત કરવા માટે સિસ્ટમ સેટિંગ્સમાં તેને ઍક્સેસિબિલિટીની મંજૂરી આપો.",
  "hi-IN": "यह आधिकारिक ChatGPT ऐप है। स्क्रिप्ट नियंत्रण बहाल करने के लिए सिस्टम सेटिंग्ज़ में इसे ऐक्सेसिबिलिटी की अनुमति दें।",
  "hr-HR": "Ovo je službena aplikacija ChatGPT. Dopustite joj pristup pristupačnosti u Postavkama sustava da biste vratili kontrolu skripti.",
  "hu-HU": "Ez a hivatalos ChatGPT-alkalmazás. A szkriptvezérlés visszaállításához engedélyezd neki a Kisegítő lehetőségek használatát a Rendszerbeállításokban.",
  "hy-AM": "Սա ChatGPT-ի պաշտոնական հավելվածն է։ Սկրիպտների կառավարումը վերականգնելու համար Համակարգի կարգավորումներում թույլատրեք դրա մատչելիության հասանելիությունը։",
  "id-ID": "Ini adalah app ChatGPT resmi. Izinkan aksesibilitas untuk app ini di Pengaturan Sistem agar kontrol skrip pulih.",
  "is-IS": "Þetta er opinbera ChatGPT-forritið. Leyfðu því að nota aðgengi í Kerfisstillingum til að endurheimta stýringu á skriftum.",
  "it-IT": "Questa è l’app ufficiale di ChatGPT. Per ripristinare il controllo degli script, consentile l’accesso all’Accessibilità in Impostazioni di Sistema.",
  "ja-JP": "これは公式のChatGPTアプリです。スクリプト制御を復元するには、システム設定でこのアプリにアクセシビリティを許可してください。",
  "ka-GE": "ეს ChatGPT-ის ოფიციალური აპია. სკრიპტების მართვის აღსადგენად სისტემურ პარამეტრებში მიანიჭეთ მას წვდომადობის ნებართვა.",
  kk: "Бұл — ChatGPT ресми қолданбасы. Скрипт басқаруын қалпына келтіру үшін Жүйе параметрлерінде оған Арнайы мүмкіндіктерге рұқсат беріңіз.",
  "kn-IN": "ಇದು ಅಧಿಕೃತ ChatGPT ಆ್ಯಪ್. ಸ್ಕ್ರಿಪ್ಟ್ ನಿಯಂತ್ರಣವನ್ನು ಮರುಸ್ಥಾಪಿಸಲು ಸಿಸ್ಟಂ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಇದಕ್ಕೆ ಆಕ್ಸೆಸಿಬಿಲಿಟಿ ಅನುಮತಿ ನೀಡಿ.",
  "ko-KR": "이 앱은 공식 ChatGPT 앱입니다. 스크립트 제어를 복원하려면 시스템 설정에서 이 앱에 손쉬운 사용 권한을 허용하세요.",
  lt: "Tai oficiali „ChatGPT“ programėlė. Norėdami atkurti scenarijų valdymą, sistemos nustatymuose suteikite jai prieinamumo leidimą.",
  "lv-LV": "Šī ir oficiālā ChatGPT lietotne. Lai atjaunotu skriptu vadību, Sistēmas iestatījumos atļaujiet tai piekļuvi pieejamībai.",
  "mk-MK": "Ова е официјалната апликација ChatGPT. Дозволете ѝ пристап до Пристапност во Системските поставки за да ја вратите контролата на скриптите.",
  ml: "ഇത് ഔദ്യോഗിക ChatGPT ആപ്പാണ്. സ്ക്രിപ്റ്റ് നിയന്ത്രണം പുനഃസ്ഥാപിക്കാൻ സിസ്റ്റം ക്രമീകരണങ്ങളിൽ ഇതിന് ആക്‌സസിബിലിറ്റി അനുമതി നൽകുക.",
  mn: "Энэ бол ChatGPT-ийн албан ёсны апп юм. Скриптийн удирдлагыг сэргээхийн тулд Системийн тохиргоонд Хандалтын зөвшөөрөл олгоно уу.",
  "mr-IN": "हे अधिकृत ChatGPT अॅप आहे. स्क्रिप्ट नियंत्रण पुन्हा सुरू करण्यासाठी सिस्टम सेटिंग्जमध्ये याला अॅक्सेसिबिलिटीची परवानगी द्या.",
  "ms-MY": "Ini ialah app rasmi ChatGPT. Benarkan app ini menggunakan Kebolehcapaian dalam Tetapan Sistem untuk memulihkan kawalan skrip.",
  "my-MM": "ဤသည်မှာ တရားဝင် ChatGPT အက်ပ်ဖြစ်သည်။ စခရစ်ပ်ထိန်းချုပ်မှုကို ပြန်လည်ရရှိရန် စနစ်ဆက်တင်များတွင် ဤအက်ပ်ကို အသုံးပြုနိုင်မှု ခွင့်ပြုပါ။",
  "nb-NO": "Dette er den offisielle ChatGPT-appen. Tillat den i Systeminnstillinger under Tilgjengelighet for å gjenopprette skriptstyring.",
  "nl-NL": "Dit is de officiële ChatGPT-app. Geef deze app in Systeeminstellingen toegang tot Toegankelijkheid om scriptbediening te herstellen.",
  pa: "ਇਹ ਅਧਿਕਾਰਤ ChatGPT ਐਪ ਹੈ। ਸਕ੍ਰਿਪਟ ਕੰਟਰੋਲ ਮੁੜ ਚਾਲੂ ਕਰਨ ਲਈ ਸਿਸਟਮ ਸੈਟਿੰਗਾਂ ਵਿੱਚ ਇਸਨੂੰ ਪਹੁੰਚਯੋਗਤਾ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ।",
  "pl-PL": "To oficjalna aplikacja ChatGPT. Aby przywrócić obsługę skryptów, zezwól jej na dostęp do funkcji Dostępność w Ustawieniach systemowych.",
  "pt-BR": "Este é o app oficial do ChatGPT. Permita o acesso à Acessibilidade nos Ajustes do Sistema para restaurar o controle por scripts.",
  "pt-PT": "Esta é a app oficial do ChatGPT. Permita o acesso à Acessibilidade nas Definições do Sistema para restaurar o controlo por scripts.",
  "ro-RO": "Aceasta este aplicația oficială ChatGPT. Pentru a restabili controlul scripturilor, permiteți-i accesul la Accesibilitate în Configurări sistem.",
  "ru-RU": "Это официальное приложение ChatGPT. Чтобы восстановить управление скриптами, разрешите ему доступ к Универсальному доступу в Системных настройках.",
  "sk-SK": "Toto je oficiálna aplikácia ChatGPT. Ak chcete obnoviť ovládanie skriptov, povoľte jej v Nastaveniach systému prístup k funkcii Prístupnosť.",
  "sl-SI": "To je uradna aplikacija ChatGPT. Če želite obnoviti upravljanje skriptov, ji v Sistemske nastavitve dovolite dostop do Dostopnosti.",
  "so-SO": "Kani waa abka rasmiga ah ee ChatGPT. Si aad u soo celiso xakamaynta qoraallada, uga oggolow Helitaanka gudaha Dejinta Nidaamka.",
  "sq-AL": "Ky është aplikacioni zyrtar i ChatGPT. Për të rikthyer kontrollin e skripteve, lejoji qasjen te Aksesueshmëria në Cilësimet e sistemit.",
  "sr-RS": "Ово је званична апликација ChatGPT. Дозволите јој приступ функцији Приступачност у системским подешавањима да бисте вратили контролу скрипти.",
  "sv-SE": "Det här är den officiella ChatGPT-appen. Tillåt den under Hjälpmedel i Systeminställningar för att återställa skriptstyrningen.",
  "sw-TZ": "Hii ni programu rasmi ya ChatGPT. Iruhusu kutumia Ufikivu kwenye Mipangilio ya Mfumo ili kurejesha udhibiti wa hati za programu.",
  "ta-IN": "இது அதிகாரப்பூர்வ ChatGPT செயலி. ஸ்கிரிப்ட் கட்டுப்பாட்டை மீட்டெடுக்க, சிஸ்டம் செட்டிங்ஸில் இதற்கு அணுகல்தன்மை அனுமதி வழங்குங்கள்.",
  "te-IN": "ఇది అధికారిక ChatGPT యాప్. స్క్రిప్ట్ నియంత్రణను పునరుద్ధరించడానికి సిస్టమ్ సెట్టింగ్‌లలో దీనికి యాక్సెసిబిలిటీ అనుమతి ఇవ్వండి.",
  "th-TH": "นี่คือแอป ChatGPT อย่างเป็นทางการ โปรดอนุญาตให้แอปใช้การช่วยการเข้าถึงในการตั้งค่าระบบเพื่อคืนค่าการควบคุมสคริปต์",
  tl: "Ito ang opisyal na ChatGPT app. Payagan itong gumamit ng Accessibility sa System Settings para maibalik ang script control.",
  "tr-TR": "Bu, resmi ChatGPT uygulamasıdır. Komut dosyası denetimini geri yüklemek için Sistem Ayarları'nda bu uygulamaya Erişilebilirlik izni verin.",
  "uk-UA": "Це офіційний застосунок ChatGPT. Щоб відновити керування скриптами, дозвольте йому доступ до «Спеціальних можливостей» у Системних параметрах.",
  ur: "یہ ChatGPT کی سرکاری ایپ ہے۔ اسکرپٹ کنٹرول بحال کرنے کے لیے سسٹم سیٹنگز میں اسے قابلِ رسائی کی اجازت دیں۔",
  "vi-VN": "Đây là ứng dụng ChatGPT chính thức. Hãy cho phép ứng dụng dùng Trợ năng trong Cài đặt hệ thống để khôi phục quyền điều khiển tập lệnh.",
  en: "This is the official ChatGPT app. Allow it in System Settings to restore script control.",
  "zh-CN": "当前是官方 ChatGPT。请在系统设置中允许它的辅助功能权限，以恢复脚本控制。",
  "zh-HK": "目前這是官方 ChatGPT 應用程式。請在系統設定中允許它使用輔助功能，以恢復指令碼控制。",
  "zh-TW": "目前這是官方 ChatGPT App。請在系統設定中允許它使用輔助功能權限，以恢復腳本控制。",
};
