export type CopyKey = "open" | "exit" | "title" | "body" | "dismiss";
export type CopyTable = Record<CopyKey, string>;

// Official Codex UI locales from ../locales/*.json (plus English source).
export const COPY: Record<string, CopyTable> = {
  en: {
    open: "Open incognito window",
    exit: "Exit incognito window",
    title: "Incognito window",
    body: "Same account and settings as usual, without earlier chats. Close this window and this conversation won't leave a record.",
    dismiss: "Dismiss incognito banner",
  },
  am: {
    open: "የግል መስኮት ክፈት",
    exit: "የግል መስኮትን ውጣ",
    title: "የግል መስኮት",
    body: "መለያ እና ቅንብሮች እንደተለመደው ናቸው፣ ቀደም ያሉ ውይይቶች አይመጡም። ይህን መስኮት ሲዘጉ ይህ ውይይት አይቀመጥም።",
    dismiss: "የግል መስኮት ማስታወቂያን ዝጋ",
  },
  ar: {
    open: "فتح نافذة التصفح المتخفي",
    exit: "الخروج من نافذة التصفح المتخفي",
    title: "نافذة التصفح المتخفي",
    body: "الحساب والإعدادات كما هي عادةً، دون المحادثات السابقة. أغلق هذه النافذة ولن يُحفظ سجل هذه المحادثة.",
    dismiss: "إغلاق بانر التصفح المتخفي",
  },
  "bg-BG": {
    open: "Отваряне на прозорец инкогнито",
    exit: "Изход от прозорец инкогнито",
    title: "Прозорец инкогнито",
    body: "Акаунтът и настройките са както обикновено, без предишни разговори. Затворете този прозорец и този чат няма да остави запис.",
    dismiss: "Затваряне на банера за инкогнито",
  },
  "bn-BD": {
    open: "ইনকগনিটো উইন্ডো খুলুন",
    exit: "ইনকগনিটো উইন্ডো থেকে বেরোন",
    title: "ইনকগনিটো উইন্ডো",
    body: "অ্যাকাউন্ট ও সেটিংস আগের মতোই, আগের আলোচনা আসবে না। এই উইন্ডো বন্ধ করলে এবারের চ্যাটের রেকর্ড থাকবে না।",
    dismiss: "ইনকগনিটো ব্যানার বন্ধ করুন",
  },
  "bs-BA": {
    open: "Otvori prozor incognito",
    exit: "Izađi iz prozora incognito",
    title: "Prozor incognito",
    body: "Račun i postavke su kao i obično, bez prethodnih razgovora. Zatvorite ovaj prozor i ovaj chat neće ostaviti zapis.",
    dismiss: "Zatvori incognito banner",
  },
  "ca-ES": {
    open: "Obre una finestra d'incògnit",
    exit: "Surt de la finestra d'incògnit",
    title: "Finestra d'incògnit",
    body: "El compte i la configuració són els de sempre, sense converses anteriors. Si tanques aquesta finestra, aquest xat no deixarà cap registre.",
    dismiss: "Tanca el bàner d'incògnit",
  },
  "cs-CZ": {
    open: "Otevřít anonymní okno",
    exit: "Ukončit anonymní okno",
    title: "Anonymní okno",
    body: "Účet a nastavení jsou jako obvykle, bez předchozích konverzací. Po zavření tohoto okna se tento chat nezaznamená.",
    dismiss: "Zavřít banner anonymního okna",
  },
  "da-DK": {
    open: "Åbn inkognitovindue",
    exit: "Afslut inkognitovindue",
    title: "Inkognitovindue",
    body: "Konto og indstillinger er som sædvanlig, uden tidligere samtaler. Lukker du dette vindue, efterlader denne chat ingen optegnelse.",
    dismiss: "Luk inkognitobanner",
  },
  "de-DE": {
    open: "Inkognito-Fenster öffnen",
    exit: "Inkognito-Fenster beenden",
    title: "Inkognito-Fenster",
    body: "Konto und Einstellungen sind wie sonst, ohne frühere Unterhaltungen. Wenn du dieses Fenster schließt, bleibt von diesem Chat kein Verlauf.",
    dismiss: "Inkognito-Banner schließen",
  },
  "el-GR": {
    open: "Άνοιγμα παραθύρου ανώνυμης περιήγησης",
    exit: "Έξοδος από το παράθυρο ανώνυμης περιήγησης",
    title: "Παράθυρο ανώνυμης περιήγησης",
    body: "Ο λογαριασμός και οι ρυθμίσεις είναι όπως συνήθως, χωρίς προηγούμενες συνομιλίες. Κλείστε αυτό το παράθυρο και αυτή η συνομιλία δεν θα αφήσει εγγραφή.",
    dismiss: "Κλείσιμο του banner ανώνυμης περιήγησης",
  },
  "es-419": {
    open: "Abrir ventana de incógnito",
    exit: "Salir de la ventana de incógnito",
    title: "Ventana de incógnito",
    body: "La cuenta y la configuración son las de siempre, sin conversaciones anteriores. Si cierras esta ventana, este chat no dejará registro.",
    dismiss: "Cerrar el banner de incógnito",
  },
  "es-ES": {
    open: "Abrir ventana de incógnito",
    exit: "Salir de la ventana de incógnito",
    title: "Ventana de incógnito",
    body: "La cuenta y la configuración son las de siempre, sin conversaciones anteriores. Si cierras esta ventana, este chat no dejará registro.",
    dismiss: "Cerrar el banner de incógnito",
  },
  "et-EE": {
    open: "Ava inkognitoaken",
    exit: "Välju inkognitoaknast",
    title: "Inkognitoaken",
    body: "Konto ja seaded on tavapärased, varasemaid vestlusi kaasa ei tooda. Kui sulged selle akna, ei jää sellest vestlusest jälge.",
    dismiss: "Sulge inkognitobänner",
  },
  fa: {
    open: "باز کردن پنجره ناشناس",
    exit: "خروج از پنجره ناشناس",
    title: "پنجره ناشناس",
    body: "حساب و تنظیمات مثل همیشه است و گفتگوهای قبلی وارد نمی‌شود. با بستن این پنجره، این گفتگو ثبت نمی‌ماند.",
    dismiss: "بستن بنر پنجره ناشناس",
  },
  "fi-FI": {
    open: "Avaa incognito-ikkuna",
    exit: "Poistu incognito-ikkunasta",
    title: "Incognito-ikkuna",
    body: "Tili ja asetukset ovat ennallaan, aiempia keskusteluja ei tuoda. Jos suljet tämän ikkunan, tästä chatista ei jää merkintää.",
    dismiss: "Sulje incognito-banneri",
  },
  "fr-CA": {
    open: "Ouvrir une fenêtre de navigation privée",
    exit: "Quitter la fenêtre de navigation privée",
    title: "Fenêtre de navigation privée",
    body: "Le compte et les réglages sont les mêmes qu’à l’habitude, sans les conversations précédentes. Fermez cette fenêtre et ce clavardage ne laissera aucune trace.",
    dismiss: "Fermer la bannière de navigation privée",
  },
  "fr-FR": {
    open: "Ouvrir une fenêtre de navigation privée",
    exit: "Quitter la fenêtre de navigation privée",
    title: "Fenêtre de navigation privée",
    body: "Le compte et les paramètres sont les mêmes que d’habitude, sans les conversations précédentes. Fermez cette fenêtre et cette discussion ne laissera aucune trace.",
    dismiss: "Fermer la bannière de navigation privée",
  },
  "gu-IN": {
    open: "ઇનકોગ્નિટો વિન્ડો ખોલો",
    exit: "ઇનકોગ્નિટો વિન્ડોમાંથી બહાર નીકળો",
    title: "ઇનકોગ્નિટો વિન્ડો",
    body: "એકાઉન્ટ અને સેટિંગ્સ હંમેશની જેમ છે, અગાઉની વાતચીતો આવશે નહીં. આ વિન્ડો બંધ કરશો તો આ ચેટનો રેકોર્ડ રહેશે નહીં.",
    dismiss: "ઇનકોગ્નિટો બેનર બંધ કરો",
  },
  "hi-IN": {
    open: "गुप्त विंडो खोलें",
    exit: "गुप्त विंडो से बाहर निकलें",
    title: "गुप्त विंडो",
    body: "खाता और सेटिंग्स वैसे ही हैं, पिछली बातचीत नहीं आएगी। यह विंडो बंद करने पर इस चैट का रिकॉर्ड नहीं रहेगा।",
    dismiss: "गुप्त विंडो बैनर बंद करें",
  },
  "hr-HR": {
    open: "Otvori prozor incognito",
    exit: "Izađi iz prozora incognito",
    title: "Prozor incognito",
    body: "Račun i postavke su kao i obično, bez prethodnih razgovora. Zatvorite ovaj prozor i ovaj chat neće ostaviti zapis.",
    dismiss: "Zatvori incognito banner",
  },
  "hu-HU": {
    open: "Inkognitóablak megnyitása",
    exit: "Kilépés az inkognitóablakból",
    title: "Inkognitóablak",
    body: "A fiók és a beállítások a szokásosak, korábbi beszélgetések nélkül. Ha bezárod ezt az ablakot, ebből a csevegésből nem marad nyom.",
    dismiss: "Inkognitó banner bezárása",
  },
  "hy-AM": {
    open: "Բացել գաղտնի պատուհանը",
    exit: "Դուրս գալ գաղտնի պատուհանից",
    title: "Գաղտնի պատուհան",
    body: "Հաշիվն ու կարգավորումները սովորականի պես են, նախորդ զրույցները չեն բերվի։ Այս պատուհանը փակելիս այս զրույցը գրառում չի թողնի։",
    dismiss: "Փակել գաղտնի պատուհանի դրոշակը",
  },
  "id-ID": {
    open: "Buka jendela penyamaran",
    exit: "Keluar dari jendela penyamaran",
    title: "Jendela penyamaran",
    body: "Akun dan pengaturan sama seperti biasa, tanpa percakapan sebelumnya. Tutup jendela ini dan obrolan ini tidak akan meninggalkan catatan.",
    dismiss: "Tutup banner jendela penyamaran",
  },
  "is-IS": {
    open: "Opna huliðsglugga",
    exit: "Hætta í huliðsglugga",
    title: "Huliðsgluggi",
    body: "Aðgangur og stillingar eru eins og venjulega, án fyrri spjalla. Ef þú lokar þessum glugga skilur þetta spjall ekkert eftir sig.",
    dismiss: "Loka huliðsbanneri",
  },
  "it-IT": {
    open: "Apri finestra in incognito",
    exit: "Esci dalla finestra in incognito",
    title: "Finestra in incognito",
    body: "Account e impostazioni sono quelli di sempre, senza le chat precedenti. Chiudi questa finestra e questa conversazione non lascerà traccia.",
    dismiss: "Chiudi il banner in incognito",
  },
  "ja-JP": {
    open: "シークレットウィンドウを開く",
    exit: "シークレットウィンドウを終了",
    title: "シークレットウィンドウ",
    body: "アカウントと設定は普段と同じで、以前の会話は引き継ぎません。このウィンドウを閉じると、今回のチャットは残りません。",
    dismiss: "シークレットウィンドウのバナーを閉じる",
  },
  "ka-GE": {
    open: "ინკოგნიტო ფანჯრის გახსნა",
    exit: "ინკოგნიტო ფანჯრიდან გასვლა",
    title: "ინკოგნიტო ფანჯარა",
    body: "ანგარიში და პარამეტრები ჩვეულებრივია, წინა საუბრები არ შემოვა. ამ ფანჯრის დახურვის შემდეგ ეს ჩატი ჩანაწერს არ დატოვებს.",
    dismiss: "ინკოგნიტო ბანერის დახურვა",
  },
  kk: {
    open: "Инкогнито терезесін ашу",
    exit: "Инкогнито терезесінен шығу",
    title: "Инкогнито терезесі",
    body: "Тіркелгі мен баптаулар әдеттегідей, бұрынғы әңгімелер кірмейді. Бұл терезені жапсаңыз, осы чат жазба қалдырмайды.",
    dismiss: "Инкогнито баннерін жабу",
  },
  "kn-IN": {
    open: "ಅಜ್ಞಾತ ವಿಂಡೋ ತೆರೆಯಿರಿ",
    exit: "ಅಜ್ಞಾತ ವಿಂಡೋದಿಂದ ನಿರ್ಗಮಿಸಿ",
    title: "ಅಜ್ಞಾತ ವಿಂಡೋ",
    body: "ಖಾತೆ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಎಂದಿನಂತೆ, ಹಿಂದಿನ ಸಂಭಾಷಣೆಗಳು ಬರುವುದಿಲ್ಲ. ಈ ವಿಂಡೋ ಮುಚ್ಚಿದರೆ ಈ ಚಾಟ್‌ನ ದಾಖಲೆ ಉಳಿಯುವುದಿಲ್ಲ.",
    dismiss: "ಅಜ್ಞಾತ ಬ್ಯಾನರ್ ಮುಚ್ಚಿ",
  },
  "ko-KR": {
    open: "시크릿 창 열기",
    exit: "시크릿 창 나가기",
    title: "시크릿 창",
    body: "계정과 설정은 평소와 같고, 이전 대화는 가져오지 않습니다. 창을 닫으면 이번 채팅은 남지 않습니다.",
    dismiss: "시크릿 창 배너 닫기",
  },
  lt: {
    open: "Atidaryti inkognito langą",
    exit: "Išeiti iš inkognito lango",
    title: "Inkognito langas",
    body: "Paskyra ir nustatymai tokie patys kaip įprastai, ankstesni pokalbiai neperkeliami. Užvėrus šį langą šis pokalbis nepaliks įrašo.",
    dismiss: "Uždaryti inkognito juostą",
  },
  "lv-LV": {
    open: "Atvērt inkognito logu",
    exit: "Iziet no inkognito loga",
    title: "Inkognito logs",
    body: "Konts un iestatījumi ir kā parasti, bez iepriekšējām sarunām. Aizverot šo logu, šī tērzēšana neatstās ierakstu.",
    dismiss: "Aizvērt inkognito baneri",
  },
  "mk-MK": {
    open: "Отвори прозорец инкогнито",
    exit: "Излези од прозорецот инкогнито",
    title: "Прозорец инкогнито",
    body: "Сметката и поставките се како и обично, без претходни разговори. Ако го затворите овој прозорец, овој разговор нема да остави запис.",
    dismiss: "Затвори го банерот за инкогнито",
  },
  ml: {
    open: "ഇൻകോഗ്നിറ്റോ വിൻഡോ തുറക്കുക",
    exit: "ഇൻകോഗ്നിറ്റോ വിൻഡോയിൽ നിന്ന് പുറത്തുകടക്കുക",
    title: "ഇൻകോഗ്നിറ്റോ വിൻഡോ",
    body: "അക്കൗണ്ടും ക്രമീകരണങ്ങളും പതിവുപോലെയാണ്, മുമ്പത്തെ സംഭാഷണങ്ങൾ വരില്ല. ഈ വിൻഡോ അടച്ചാൽ ഈ ചാറ്റിന്റെ രേഖ നിലനിൽക്കില്ല.",
    dismiss: "ഇൻകോഗ്നിറ്റോ ബാനർ അടയ്ക്കുക",
  },
  mn: {
    open: "Нууц цонх нээх",
    exit: "Нууц цонхноос гарах",
    title: "Нууц цонх",
    body: "Бүртгэл, тохиргоо хэвийнхээ л адил, өмнөх яриа орж ирэхгүй. Энэ цонхыг хаавал энэ чат үлдэхгүй.",
    dismiss: "Нууц цонхны баннерыг хаах",
  },
  "mr-IN": {
    open: "गुप्त विंडो उघडा",
    exit: "गुप्त विंडोमधून बाहेर पडा",
    title: "गुप्त विंडो",
    body: "खाते आणि सेटिंग्ज नेहमीप्रमाणे आहेत, आधीच्या संभाषणांचा समावेश होणार नाही. हे विंडो बंद केल्यावर या चॅटची नोंद राहणार नाही.",
    dismiss: "गुप्त बॅनर बंद करा",
  },
  "ms-MY": {
    open: "Buka tetingkap inkognito",
    exit: "Keluar dari tetingkap inkognito",
    title: "Tetingkap inkognito",
    body: "Akaun dan tetapan sama seperti biasa, tanpa perbualan terdahulu. Tutup tetingkap ini dan sembang ini tidak akan meninggalkan rekod.",
    dismiss: "Tutup sepanduk inkognito",
  },
  "my-MM": {
    open: "လျှို့ဝှက်ဝင်းဒိုးဖွင့်ရန်",
    exit: "လျှို့ဝှက်ဝင်းဒိုးမှ ထွက်ရန်",
    title: "လျှို့ဝှက်ဝင်းဒိုး",
    body: "အကောင့်နှင့် ဆက်တင်များသည် ပုံမှန်အတိုင်းဖြစ်ပြီး ယခင်စကားဝိုင်းများ မပါဝင်ပါ။ ဤဝင်းဒိုးကို ပိတ်လိုက်လျှင် ဤချတ်မှတ်တမ်း ကျန်မည်မဟုတ်ပါ။",
    dismiss: "လျှို့ဝှက်နဖူးစည်းကို ပိတ်ရန်",
  },
  "nb-NO": {
    open: "Åpne inkognitovindu",
    exit: "Avslutt inkognitovindu",
    title: "Inkognitovindu",
    body: "Konto og innstillinger er som vanlig, uten tidligere samtaler. Lukker du dette vinduet, etterlater ikke denne chatten noen oppføring.",
    dismiss: "Lukk inkognitobanneret",
  },
  "nl-NL": {
    open: "Incognitovenster openen",
    exit: "Incognitovenster sluiten",
    title: "Incognitovenster",
    body: "Account en instellingen zijn hetzelfde als anders, zonder eerdere gesprekken. Sluit dit venster en deze chat laat geen record achter.",
    dismiss: "Incognitobanner sluiten",
  },
  pa: {
    open: "ਇਨਕੌਗਨੀਟੋ ਵਿੰਡੋ ਖੋਲ੍ਹੋ",
    exit: "ਇਨਕੌਗਨੀਟੋ ਵਿੰਡੋ ਤੋਂ ਬਾਹਰ ਜਾਓ",
    title: "ਇਨਕੌਗਨੀਟੋ ਵਿੰਡੋ",
    body: "ਖਾਤਾ ਅਤੇ ਸੈਟਿੰਗਾਂ ਆਮ ਵਾਂਗ ਹਨ, ਪਿਛਲੀਆਂ ਗੱਲਾਂ ਨਹੀਂ ਆਉਣਗੀਆਂ। ਇਹ ਵਿੰਡੋ ਬੰਦ ਕਰਨ ਤੇ ਇਸ ਚੈਟ ਦਾ ਰਿਕਾਰਡ ਨਹੀਂ ਰਹੇਗਾ।",
    dismiss: "ਇਨਕੌਗਨੀਟੋ ਬੈਨਰ ਬੰਦ ਕਰੋ",
  },
  "pl-PL": {
    open: "Otwórz okno incognito",
    exit: "Zamknij okno incognito",
    title: "Okno incognito",
    body: "Konto i ustawienia są jak zwykle, bez wcześniejszych rozmów. Zamknij to okno, a ta rozmowa nie pozostawi zapisu.",
    dismiss: "Zamknij baner incognito",
  },
  "pt-BR": {
    open: "Abrir janela anônima",
    exit: "Sair da janela anônima",
    title: "Janela anônima",
    body: "A conta e as configurações são as de sempre, sem conversas anteriores. Feche esta janela e este chat não deixará registro.",
    dismiss: "Fechar o banner da janela anônima",
  },
  "pt-PT": {
    open: "Abrir janela de navegação privada",
    exit: "Sair da janela de navegação privada",
    title: "Janela de navegação privada",
    body: "A conta e as definições são as do costume, sem conversas anteriores. Feche esta janela e esta conversa não deixará registo.",
    dismiss: "Fechar o banner de navegação privada",
  },
  "ro-RO": {
    open: "Deschide fereastra incognito",
    exit: "Ieși din fereastra incognito",
    title: "Fereastră incognito",
    body: "Contul și setările sunt ca de obicei, fără conversațiile anterioare. Dacă închizi această fereastră, acest chat nu va lăsa nicio înregistrare.",
    dismiss: "Închide bannerul incognito",
  },
  "ru-RU": {
    open: "Открыть окно инкогнито",
    exit: "Выйти из окна инкогнито",
    title: "Окно инкогнито",
    body: "Аккаунт и настройки как обычно, без прошлых диалогов. Закройте это окно — и этот чат не оставит записи.",
    dismiss: "Закрыть баннер окна инкогнито",
  },
  "sk-SK": {
    open: "Otvoriť anonymné okno",
    exit: "Ukončiť anonymné okno",
    title: "Anonymné okno",
    body: "Účet a nastavenia sú ako zvyčajne, bez predchádzajúcich konverzácií. Ak toto okno zatvoríte, tento chat nezanechá záznam.",
    dismiss: "Zavrieť banner anonymného okna",
  },
  "sl-SI": {
    open: "Odpri okno brez beleženja",
    exit: "Zapusti okno brez beleženja",
    title: "Okno brez beleženja",
    body: "Račun in nastavitve so kot običajno, brez prejšnjih pogovorov. Če zaprete to okno, ta klepet ne pusti zapisa.",
    dismiss: "Zapri pasico okna brez beleženja",
  },
  "so-SO": {
    open: "Fur daaqadda qarsoodiga",
    exit: "Ka bax daaqadda qarsoodiga",
    title: "Daaqadda qarsoodiga",
    body: "Akoonka iyo dejinta waa sidii caadiga ahayd, wadahadalladii hore ma imanayaan. Daaqaddan xir, sheekadani ma reebi doonto diiwaan.",
    dismiss: "Xir calanka daaqadda qarsoodiga",
  },
  "sq-AL": {
    open: "Hap dritaren inkognito",
    exit: "Dil nga dritarja inkognito",
    title: "Dritare inkognito",
    body: "Llogaria dhe cilësimet janë si zakonisht, pa bisedat e mëparshme. Mbylleni këtë dritare dhe ky bisedim nuk do të lërë regjistër.",
    dismiss: "Mbyll banderolën inkognito",
  },
  "sr-RS": {
    open: "Отвори прозор инкогнито",
    exit: "Изађи из прозора инкогнито",
    title: "Прозор инкогнито",
    body: "Налог и подешавања су као обично, без претходних разговора. Ако затворите овај прозор, овај ћаскање неће оставити запис.",
    dismiss: "Затвори банер инкогнито",
  },
  "sv-SE": {
    open: "Öppna inkognitofönster",
    exit: "Avsluta inkognitofönster",
    title: "Inkognitofönster",
    body: "Konto och inställningar är som vanligt, utan tidigare samtal. Stänger du det här fönstret lämnar den här chatten ingen post.",
    dismiss: "Stäng inkognitobannern",
  },
  "sw-TZ": {
    open: "Fungua dirisha la faragha",
    exit: "Toka kwenye dirisha la faragha",
    title: "Dirisha la faragha",
    body: "Akaunti na mipangilio ni kama kawaida, bila mazungumzo ya awali. Funga dirisha hili na gumzo hili halitaacha rekodi.",
    dismiss: "Funga bango la dirisha la faragha",
  },
  "ta-IN": {
    open: "மறைநிலை சாளரத்தைத் திற",
    exit: "மறைநிலை சாளரத்திலிருந்து வெளியேறு",
    title: "மறைநிலை சாளரம்",
    body: "கணக்கும் அமைப்புகளும் வழக்கம் போலவே; முந்தைய உரையாடல்கள் வராது. இந்தச் சாளரத்தை மூடினால் இந்த அரட்டையின் பதிவு இருக்காது.",
    dismiss: "மறைநிலை பதாகையை மூடு",
  },
  "te-IN": {
    open: "అజ్ఞాత విండోను తెరవండి",
    exit: "అజ్ఞాత విండో నుంచి నిష్క్రమించండి",
    title: "అజ్ఞాత విండో",
    body: "ఖాతా, సెట్టింగ్‌లు ఎప్పటిలాగే ఉంటాయి; మునుపటి సంభాషణలు రావు. ఈ విండో మూస్తే ఈ చాట్ రికార్డు ఉండదు.",
    dismiss: "అజ్ఞాత బ్యానర్‌ను మూసివేయండి",
  },
  "th-TH": {
    open: "เปิดหน้าต่างไม่ระบุตัวตน",
    exit: "ออกจากหน้าต่างไม่ระบุตัวตน",
    title: "หน้าต่างไม่ระบุตัวตน",
    body: "บัญชีและการตั้งค่าเหมือนเดิม จะไม่ดึงบทสนทนาก่อนหน้า ปิดหน้าต่างนี้แล้วแชทนี้จะไม่เหลือบันทึก",
    dismiss: "ปิดแบนเนอร์หน้าต่างไม่ระบุตัวตน",
  },
  tl: {
    open: "Buksan ang incognito window",
    exit: "Lumabas sa incognito window",
    title: "Incognito window",
    body: "Pareho pa rin ang account at settings, walang dating usapan. Isara ang window na ito at hindi mag-iiwan ng record ang chat na ito.",
    dismiss: "Isara ang incognito banner",
  },
  "tr-TR": {
    open: "Gizli pencere aç",
    exit: "Gizli pencereden çık",
    title: "Gizli pencere",
    body: "Hesap ve ayarlar her zamanki gibi; önceki sohbetler gelmez. Bu pencereyi kapatırsanız bu sohbet kayıt bırakmaz.",
    dismiss: "Gizli pencere banner’ını kapat",
  },
  "uk-UA": {
    open: "Відкрити вікно інкогніто",
    exit: "Вийти з вікна інкогніто",
    title: "Вікно інкогніто",
    body: "Обліковий запис і налаштування як завжди, без попередніх розмов. Закрийте це вікно — і цей чат не залишить запису.",
    dismiss: "Закрити банер вікна інкогніто",
  },
  ur: {
    open: "خفیہ ونڈو کھولیں",
    exit: "خفیہ ونڈو سے باہر نکلیں",
    title: "خفیہ ونڈو",
    body: "اکاؤنٹ اور سیٹنگز ویسی ہی ہیں، پچھلی گفتگو نہیں آئے گی۔ یہ ونڈو بند کرنے پر اس چیٹ کا ریکارڈ نہیں رہے گا۔",
    dismiss: "خفیہ بینر بند کریں",
  },
  "vi-VN": {
    open: "Mở cửa sổ ẩn danh",
    exit: "Thoát cửa sổ ẩn danh",
    title: "Cửa sổ ẩn danh",
    body: "Tài khoản và cài đặt như bình thường, không mang theo hội thoại cũ. Đóng cửa sổ này thì cuộc trò chuyện này sẽ không để lại bản ghi.",
    dismiss: "Đóng banner cửa sổ ẩn danh",
  },
  "zh-CN": {
    open: "打开无痕窗口",
    exit: "退出无痕窗口",
    title: "无痕窗口",
    body: "账号和设置跟平时一样，不会带入之前的对话。关闭窗口后，这次聊天不会留下记录。",
    dismiss: "关闭无痕窗口横幅",
  },
  "zh-HK": {
    open: "開啟無痕視窗",
    exit: "離開無痕視窗",
    title: "無痕視窗",
    body: "帳戶和設定跟平時一樣，不會帶入之前的對話。關閉視窗後，今次聊天不會留下紀錄。",
    dismiss: "關閉無痕視窗橫額",
  },
  "zh-TW": {
    open: "開啟無痕視窗",
    exit: "離開無痕視窗",
    title: "無痕視窗",
    body: "帳號和設定跟平時一樣，不會帶入之前的對話。關閉視窗後，這次聊天不會留下紀錄。",
    dismiss: "關閉無痕視窗橫幅",
  },
};

const DEFAULT_BY_LANGUAGE: Record<string, string> = {
  bg: "bg-BG",
  bn: "bn-BD",
  bs: "bs-BA",
  ca: "ca-ES",
  cs: "cs-CZ",
  da: "da-DK",
  de: "de-DE",
  el: "el-GR",
  es: "es-419",
  et: "et-EE",
  fi: "fi-FI",
  fr: "fr-FR",
  gu: "gu-IN",
  hi: "hi-IN",
  hr: "hr-HR",
  hu: "hu-HU",
  hy: "hy-AM",
  id: "id-ID",
  is: "is-IS",
  it: "it-IT",
  ja: "ja-JP",
  ka: "ka-GE",
  kn: "kn-IN",
  ko: "ko-KR",
  lv: "lv-LV",
  mk: "mk-MK",
  mr: "mr-IN",
  ms: "ms-MY",
  my: "my-MM",
  nb: "nb-NO",
  no: "nb-NO",
  nl: "nl-NL",
  pl: "pl-PL",
  pt: "pt-BR",
  ro: "ro-RO",
  ru: "ru-RU",
  sk: "sk-SK",
  sl: "sl-SI",
  so: "so-SO",
  sq: "sq-AL",
  sr: "sr-RS",
  sv: "sv-SE",
  sw: "sw-TZ",
  ta: "ta-IN",
  te: "te-IN",
  th: "th-TH",
  tr: "tr-TR",
  uk: "uk-UA",
  vi: "vi-VN",
  zh: "zh-CN",
};

export function resolveLocale(raw: string): string {
  const normalized = raw.trim().replaceAll("_", "-");
  if (!normalized) return "en";
  if (COPY[normalized]) return normalized;
  const lower = normalized.toLowerCase();
  const exact = Object.keys(COPY).find((key) => key.toLowerCase() === lower);
  if (exact) return exact;
  if (lower.startsWith("zh-hant-hk") || lower.startsWith("zh-hk")) return "zh-HK";
  if (lower.startsWith("zh-hant") || lower.startsWith("zh-tw")) return "zh-TW";
  if (lower.startsWith("zh")) return "zh-CN";
  if (lower === "en" || lower.startsWith("en-")) return "en";
  const language = lower.split("-")[0] ?? "en";
  if (COPY[language]) return language;
  if (DEFAULT_BY_LANGUAGE[language] && COPY[DEFAULT_BY_LANGUAGE[language]]) {
    return DEFAULT_BY_LANGUAGE[language];
  }
  const regional = Object.keys(COPY).find((key) => key.toLowerCase().startsWith(`${language}-`));
  return regional ?? "en";
}

export function translate(locale: string, key: CopyKey): string {
  return COPY[resolveLocale(locale)]?.[key] ?? COPY.en[key];
}
